DATA LIST FILE='C:\COUNTRIES\NG81\NGPR81FL.DAT' RECORDS=1
  /
  HHID        1-12   (A)
  HVIDX      13-14  
  HV000      15-17   (A)
  HV001      18-23  
  HV002      24-29  
  HV003      30-32  
  HV004      33-36  
  HV005      37-44  
  HV006      45-46  
  HV007      47-50  
  HV008      51-54  
  HV008A     55-59  
  HV009      60-61  
  HV010      62-63  
  HV011      64-65  
  HV012      66-67  
  HV013      68-69  
  HV014      70-71  
  HV015      72-72  
  HV016      73-74  
  HV017      75-75  
  HV018      76-80  
  HV019      81-83  
  HV020      84-84  
  HV021      85-88  
  HV022      89-92  
  HV023      93-94  
  HV024      95-96  
  HV025      97-97  
  HV026      98-98  
  HV027      99-99  
  HV028     100-107 
  HV030     108-112 
  HV031     113-117 
  HV032     118-120 
  HV035     121-122 
  HV040     123-126 
  HV041     127-128 
  HV042     129-129 
  HV045A    130-132 
  HV045B    133-135 
  HV045C    136-138 
  HV046     139-139 
  HV047     140-144 
  HV801     145-148 
  HV802     149-152 
  HV803     153-154 
  HV804     155-155 
  HV807D    156-157 
  HV807M    158-159 
  HV807Y    160-163 
  HV807C    164-167 
  HV807A    168-172 
  HV201     173-174 
  HV202     175-176 
  HV201A    177-177 
  HV204     178-180 
  HV205     181-182 
  HV206     183-183 
  HV207     184-184 
  HV208     185-185 
  HV209     186-186 
  HV210     187-187 
  HV211     188-188 
  HV212     189-189 
  HV213     190-191 
  HV214     192-193 
  HV215     194-195 
  HV216     196-197 
  HV217     198-198 
  HV218     199-200 
  HV219     201-201 
  HV220     202-203 
  HV221     204-204 
  HV222     205-206 
  HV223     207-208 
  HV225     209-209 
  HV226     210-211 
  HV227     212-212 
  HV228     213-213 
  HV235     214-214 
  HV238     215-216 
  HV238A    217-217 
  HV243A    218-218 
  HV243B    219-219 
  HV243C    220-220 
  HV243D    221-221 
  HV243E    222-222 
  HV244     223-223 
  HV245     224-226 
  HV246     227-227 
  HV246A    228-229 
  HV246B    230-231 
  HV246C    232-233 
  HV246D    234-235 
  HV246E    236-237 
  HV246F    238-239 
  HV246G    240-241 
  HV246H    242-243 
  HV246I    244-245 
  HV246J    246-247 
  HV246K    248-249 
  HV247     250-250 
  HV270     251-251 
  HV271     252-259 
  HV270A    260-260 
  HV271A    261-268 
  HML1      269-270 
  HML1A     271-271 
  HML2      272-273 
  SHLGA     274-276 
  SHTSUPERV  277-280 
  SHREGION  281-281 
  SHBONNY   282-282 
  SH116G    283-283 
  SH116H    284-284 
  SH116I    285-285 
  SH116J    286-286 
  SH116K    287-287 
  SH116L    288-288 
  SH116M    289-289 
  SH116N    290-290 
  SH116O    291-291 
  SH117H    292-292 
  SH117I    293-293 
  SH119     294-294 
  HV101     295-296 
  HV102     297-297 
  HV103     298-298 
  HV104     299-299 
  HV105     300-301 
  HV117     302-302 
  HV120     303-303 
  HC0       304-305 
  HC1       306-307 
  HC1A      308-312 
  HC16      313-314 
  HC17      315-316 
  HC18      317-318 
  HC19      319-322 
  HC20      323-327 
  HC21      328-332 
  HC27      333-333 
  HC30      334-335 
  HC31      336-339 
  HC32      340-343 
  HC32A     344-348 
  HC33      349-349 
  HC51      350-351 
  HC52      352-352 
  HC53      353-355 
  HC55      356-356 
  HC56      357-359 
  HC57      360-360 
  HC58      361-361 
  HC60      362-364 
  HC61      365-365 
  HC62      366-367 
  HC63      368-370 
  HC64      371-372 
  HC68      373-373 
  SB110B    374-374 
  SB110C    375-379 
  SB110E    380-380 
  SB110F    381-385 
  HMLIDX    386-387 
  HML3      388-388 
  HML4      389-390 
  HML5      391-391 
  HML6      392-392 
  HML7      393-394 
  HML8      395-395 
  HML9      396-397 
  HML10     398-398 
  HML11     399-399 
  HML21     400-400 
  HMLA      401-402 
  HMLB      403-404 
  HMLC      405-406 
  HMLD      407-408 
  HMLE      409-410 
  HML22     411-411 
  HML23     412-413 
  SH130     414-415 
  HMHIDX    416-417 
  HML12     418-418 
  HML13     419-419 
  HML14     420-420 
  HML15     421-421 
  HML16     422-423 
  HML16A    424-425 
  HML17     426-426 
  HML18     427-427 
  HML19     428-428 
  HML20     429-429 
  HML30     430-431 
  HML31     432-432 
  HML32     433-433 
  HML32A    434-434 
  HML32B    435-435 
  HML32C    436-436 
  HML32D    437-437 
  HML32E    438-438 
  HML32F    439-439 
  HML32G    440-440 
  HML33     441-441 
  HML34     442-446  (A)
  HML35     447-447 
  HML36     448-452 
  HML37A    453-453 
  HML37B    454-454 
  HML37C    455-455 
  HML37D    456-456 
  HML37E    457-457 
  HML37F    458-458 
  HML37G    459-459 
  HML37H    460-460 
  HML37I    461-461 
  HML37J    462-462 
  HML37K    463-463 
  HML37L    464-464 
  HML37M    465-465 
  HML38     466-466 
  HML39     467-467 
  HML40     468-472 
 .
VARIABLE LABELS
   HHID     "Case Identification"
  /HVIDX    "Line number"
  /HV000    "Country code and phase"
  /HV001    "Cluster number"
  /HV002    "Household number"
  /HV003    "Respondent's line number (answering Household questionnaire)"
  /HV004    "Ultimate area unit"
  /HV005    "Household sample weight (6 decimals)"
  /HV006    "Month of interview"
  /HV007    "Year of interview"
  /HV008    "Date of interview (CMC)"
  /HV008A   "Date of interview Century Day Code (CDC)"
  /HV009    "Number of household members"
  /HV010    "Number of eligible women in household"
  /HV011    "NA - Number of eligible men in household"
  /HV012    "Number of de jure members"
  /HV013    "Number of de facto members"
  /HV014    "Number of children 5 and under (de jure)"
  /HV015    "Result of household interview"
  /HV016    "Day of interview"
  /HV017    "Number of visits"
  /HV018    "Interviewer identification"
  /HV019    "NA - Keyer identification"
  /HV020    "Ever-married sample"
  /HV021    "Primary sampling unit"
  /HV022    "Sample strata for sampling errors"
  /HV023    "Stratification used in sample design"
  /HV024    "Region"
  /HV025    "Type of place of residence"
  /HV026    "NA - Place of residence"
  /HV027    "Household selected for male interview"
  /HV028    "Household weight for male subsample (6 decimals)"
  /HV030    "Field supervisor"
  /HV031    "NA - Field editor"
  /HV032    "NA - Office editor"
  /HV035    "Number of eligible children for height and weight"
  /HV040    "Cluster altitude in meters"
  /HV041    "NA - Total adults measured"
  /HV042    "Household selected for hemoglobin"
  /HV045A   "Language of questionnaire"
  /HV045B   "Language of interview"
  /HV045C   "Native language of respondent"
  /HV046    "Translator used"
  /HV047    "Team number"
  /HV801    "Time interview started (hhmm - 24 hour clock)"
  /HV802    "Time interview ended (hhmm - 24 hour clock)"
  /HV803    "Length of interview in minutes"
  /HV804    "Number of visits for biomarker"
  /HV807D   "Day of biomarker visit"
  /HV807M   "Month of biomarker visit"
  /HV807Y   "Year of biomarker visit"
  /HV807C   "Date of biomarker (CMC)"
  /HV807A   "Date of biomarker Century Day Code (CDC)"
  /HV201    "Source of drinking water"
  /HV202    "Source of non-drinking water"
  /HV201A   "NA - Water not available for at least a day last two weeks"
  /HV204    "Time to get to water source (minutes)"
  /HV205    "Type of toilet facility"
  /HV206    "Has electricity"
  /HV207    "Has radio"
  /HV208    "Has television"
  /HV209    "Has refrigerator"
  /HV210    "Has bicycle"
  /HV211    "Has motorcycle/scooter"
  /HV212    "Has car/truck"
  /HV213    "Main floor material"
  /HV214    "Main wall material"
  /HV215    "Main roof material"
  /HV216    "Number of rooms used for sleeping"
  /HV217    "Relationship structure"
  /HV218    "Line number of head of household"
  /HV219    "Sex of head of household"
  /HV220    "Age of head of household"
  /HV221    "Has telephone (land-line)"
  /HV222    "Type of cookstove"
  /HV223    "Type of cooking fuel"
  /HV225    "Share toilet with other households"
  /HV226    "Type of cooking fuel"
  /HV227    "Has mosquito bed net for sleeping"
  /HV228    "Children under 5 slept under mosquito bed net last night"
  /HV235    "Location of source for water"
  /HV238    "Number of households sharing toilet"
  /HV238A   "Location of toilet facility"
  /HV243A   "Has mobile telephone"
  /HV243B   "Has watch"
  /HV243C   "Has animal-drawn cart"
  /HV243D   "Has boat with a motor"
  /HV243E   "Has a computer"
  /HV244    "Owns land usable for agriculture"
  /HV245    "Hectares of agricultural land (1 decimal)"
  /HV246    "Owns livestock, herds or farm animals"
  /HV246A   "Owns cattle"
  /HV246B   "Owns cows/ bulls"
  /HV246C   "Owns horses/ donkeys/ mules"
  /HV246D   "Owns goats"
  /HV246E   "Owns sheep"
  /HV246F   "Owns chickens/poultry"
  /HV246G   "Owns pigs"
  /HV246H   "Owns camels"
  /HV246I   "NA - Owns CS"
  /HV246J   "NA - Owns CS"
  /HV246K   "NA - Owns CS"
  /HV247    "Has bank account"
  /HV270    "Wealth index combined"
  /HV271    "Wealth index factor score combined (5 decimals)"
  /HV270A   "Wealth index for urban/rural"
  /HV271A   "Wealth index factor score for urban/rural (5 decimals)"
  /HML1     "Number of mosquito bed nets"
  /HML1A    "Number of mosquito bed nets with specific information"
  /HML2     "Number of children under mosquito bed net previous night"
  /SHLGA    "Local government area"
  /SHTSUPERV "Team supervisor number"
  /SHREGION "Region"
  /SHBONNY  "Bonny State"
  /SH116G   "Has table"
  /SH116H   "Has chair"
  /SH116I   "Has bed"
  /SH116J   "Has sofa"
  /SH116K   "Has cupboard"
  /SH116L   "Has air conditioner"
  /SH116M   "Has electric iron"
  /SH116N   "Has generator"
  /SH116O   "Has fan"
  /SH117H   "Has canoe"
  /SH117I   "Has keke napep"
  /SH119    "Used mobile phone for financial transactions"
  /HV101    "Relationship to head"
  /HV102    "Usual resident"
  /HV103    "Slept last night"
  /HV104    "Sex of household member"
  /HV105    "Age of household members"
  /HV117    "Eligibility for female interview"
  /HV120    "Children eligibility for height/weight and hemoglobin"
  /HC0      "Index to Household Schedule"
  /HC1      "Child's age in months"
  /HC1A     "Child's age in days"
  /HC16     "Day of birth"
  /HC17     "Date measured (day)"
  /HC18     "Date measured (month)"
  /HC19     "Date measured (year)"
  /HC20     "Century Day Code (CDC) of measurement"
  /HC21     "Fieldworker measurer code"
  /HC27     "Sex"
  /HC30     "Month of birth"
  /HC31     "Year of birth"
  /HC32     "Date of birth (CMC)"
  /HC32A    "Century Day Code (CDC) of birth"
  /HC33     "Completeness of HC32 information"
  /HC51     "Line number of parent/caretaker"
  /HC52     "Read consent statement - hemoglobin"
  /HC53     "Hemoglobin level (g/dl - 1 decimal)"
  /HC55     "Result of measurement - hemoglobin"
  /HC56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HC57     "Anemia level"
  /HC58     "NA - Agrees to referral - anemia"
  /HC60     "Mother's line number (woman's questionnaire)"
  /HC61     "Mother's highest educational level"
  /HC62     "Mother's highest year of education"
  /HC63     "Preceding birth interval (months)"
  /HC64     "Birth order number"
  /HC68     "Mother's highest educational level (for preliminary and final report)"
  /SB110B   "Read consent statement for DBS"
  /SB110C   "Fieldworker measurer code for DBS"
  /SB110E   "Read consent statement for additional testing"
  /SB110F   "Fieldworker measurer code for additional testing"
  /HMLIDX   "Mosquito Bed Net Designation Number"
  /HML3     "Net observed by interviewer"
  /HML4     "Months ago net obtained"
  /HML5     "NA - Net treated with insecticide when bought"
  /HML6     "NA - Net treatment status"
  /HML7     "Brand of net"
  /HML8     "NA - Net treated since received"
  /HML9     "NA - Time since last re-treatment (months)"
  /HML10    "Insecticide-Treated Net (ITN)"
  /HML11    "Number of persons who slept under this net"
  /HML21    "Someone slept under this net last night"
  /HMLA     "Line number of person who slept in this net"
  /HMLB     "Line number of person who slept in this net"
  /HMLC     "Line number of person who slept in this net"
  /HMLD     "Line number of person who slept in this net"
  /HMLE     "NA - Line number of person who slept in this net"
  /HML22    "Obtained net from campaign, antenatal or immunization visit"
  /HML23    "Place where net was obtained"
  /SH130    "Reason net was not used"
  /HMHIDX   "Index to Household Schedule"
  /HML12    "Type of Mosquito Bed Net(s) person slept under last night"
  /HML13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
  /HML14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
  /HML15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
  /HML16    "Corrected age from Individual file"
  /HML16A   "Age in months (for children)"
  /HML17    "Flag for age from Individual file"
  /HML18    "Pregnancy status from Individual file"
  /HML19    "Person slept under an ever-treated net"
  /HML20    "Person slept under an LLIN net"
  /HML30    "Line number of parent/caretaker (for malaria testing)"
  /HML31    "Read consent statement for malaria"
  /HML32    "Final result of malaria from blood smear test"
  /HML32A   "Presence of species: falciparum (Pf)"
  /HML32B   "Presence of species: malariae (Pm)"
  /HML32C   "Presence of species: ovale (Po)"
  /HML32D   "Presence of species: vivax (Pv)"
  /HML32E   "NA - Presence of species: CS"
  /HML32F   "NA - Presence of species: CS"
  /HML32G   "NA - Presence of species: CS"
  /HML33    "Result of malaria measurement"
  /HML34    "Bar code for blood smear sample"
  /HML35    "Result of malaria rapid test"
  /HML36    "Fieldworker measurer code for malaria"
  /HML37A   "Suffer from illness/symptom: extreme weakness"
  /HML37B   "Suffer from illness/symptom: heart problems"
  /HML37C   "Suffer from illness/symptom: loss of consciousness"
  /HML37D   "Suffer from illness/symptom: rapid or difficult breathing"
  /HML37E   "Suffer from illness/symptom: seizures"
  /HML37F   "Suffer from illness/symptom: abnormal bleeding"
  /HML37G   "Suffer from illness/symptom: jaundice or yellow skin"
  /HML37H   "Suffer from illness/symptom: dark urine"
  /HML37I   "Suffer from illness/symptom: vomiting"
  /HML37J   "Suffer from illness/symptom: pallor"
  /HML37K   "Suffer from illness/symptom: refusal to eat"
  /HML37L   "Suffer from illness/symptom: very cold hands and feet"
  /HML37M   "NA - Suffer from illness/symptom: CS"
  /HML38    "Child taken or taking first line medicine given by health provider for malaria"
  /HML39    "Parent accept first line medicine to treat malaria"
  /HML40    "Fieldworker provided first line medicine for malaria"
 .
MISSING VALUE
   HV017    (9)
  /HV026    (9)
  /HV040    (9999)
  /HV801    (9999)
  /HV802    (9999)
  /HV803    (99)
  /HV804    (9)
  /HV201    (99)
  /HV202    (99)
  /HV201A   (9)
  /HV204    (999)
  /HV205    (99)
  /HV206    (9)
  /HV207    (9)
  /HV208    (9)
  /HV209    (9)
  /HV210    (9)
  /HV211    (9)
  /HV212    (9)
  /HV213    (99)
  /HV214    (99)
  /HV215    (99)
  /HV216    (99)
  /HV219    (9)
  /HV220    (99)
  /HV221    (9)
  /HV225    (9)
  /HV226    (99)
  /HV227    (9)
  /HV228    (9)
  /HV235    (9)
  /HV238    (99)
  /HV238A   (9)
  /HV243A   (9)
  /HV243B   (9)
  /HV243C   (9)
  /HV243D   (9)
  /HV243E   (9)
  /HV244    (9)
  /HV245    (999)
  /HV246    (9)
  /HV246A   (99)
  /HV246B   (99)
  /HV246C   (99)
  /HV246D   (99)
  /HV246E   (99)
  /HV246F   (99)
  /HV246G   (99)
  /HV246H   (99)
  /HV246I   (99)
  /HV246J   (99)
  /HV246K   (99)
  /HV247    (9)
  /HML1     (99)
  /HML2     (99)
  /SH116G   (9)
  /SH116H   (9)
  /SH116I   (9)
  /SH116J   (9)
  /SH116K   (9)
  /SH116L   (9)
  /SH116M   (9)
  /SH116N   (9)
  /SH116O   (9)
  /SH117H   (9)
  /SH117I   (9)
  /SH119    (9)
  /HV101    (99)
  /HV102    (9)
  /HV103    (9)
  /HV104    (9)
  /HV105    (99)
  /HC16     (99)
  /HC27     (9)
  /HC30     (99)
  /HC31     (9999)
  /HC51     (99)
  /HC52     (9)
  /HC53     (999)
  /HC55     (9)
  /HC56     (999)
  /HC57     (9)
  /HC58     (9)
  /HC60     (999)
  /HC61     (9)
  /HC62     (99)
  /HC63     (999)
  /HC64     (99)
  /HC68     (9)
  /SB110B   (9)
  /SB110E   (9)
  /HML3     (9)
  /HML4     (99)
  /HML5     (9)
  /HML6     (9)
  /HML7     (99)
  /HML8     (9)
  /HML9     (99)
  /HML10    (9)
  /HML11    (9)
  /HML21    (9)
  /HMLA     (99)
  /HMLB     (99)
  /HMLC     (99)
  /HML22    (9)
  /HML23    (99)
  /HML12    (9)
  /HML16    (99)
  /HML18    (9)
  /HML31    (9)
  /HML32    (9)
  /HML32A   (9)
  /HML32B   (9)
  /HML32C   (9)
  /HML32D   (9)
  /HML32E   (9)
  /HML32F   (9)
  /HML32G   (9)
  /HML33    (9)
  /HML35    (9)
  /HML37A   (9)
  /HML37B   (9)
  /HML37C   (9)
  /HML37D   (9)
  /HML37E   (9)
  /HML37F   (9)
  /HML37G   (9)
  /HML37H   (9)
  /HML37I   (9)
  /HML37J   (9)
  /HML37K   (9)
  /HML37L   (9)
  /HML37M   (9)
  /HML38    (9)
  /HML39    (9)
 .
VALUE LABELS
   HV003   
      0 "Incomplete household"
  /HV015   
      1 "Completed"
      2 "No Household member/no competent member at home"
      3 "Entire Household absent for extended period of time"
      4 "Postponed"
      5 "Refused"
      6 "Dwelling vacant or address not a dwelling"
      7 "Dwelling destroyed"
      8 "Dwelling not found"
      9 "Other"
  /HV020   
      0 "All woman sample"
      1 "Ever married sample"
  /HV022   
      1 "Abia_Urban"
      2 "Abia_Rural"
      3 "Adamawa_Urban"
      4 "Adamawa_Rural"
      5 "Akwa Ibom_Urban"
      6 "Akwa Ibom_Rural"
      7 "Anambra_Urban"
      8 "Anambra_Rural"
      9 "Bauchi_Urban"
     10 "Bauchi_Rural"
     11 "Bayelsa_Urban"
     12 "Bayelsa_Rural"
     13 "Benue_Urban"
     14 "Benue_Rural"
     15 "Borno_Urban"
     16 "Borno_Rural"
     17 "Cross River_Urban"
     18 "Cross River_Rural"
     19 "Delta_Urban"
     20 "Delta_Rural"
     21 "Ebonyi_Urban"
     22 "Ebonyi_Rural"
     23 "Edo_Urban"
     24 "Edo_Rural"
     25 "Ekiti_Urban"
     26 "Ekiti_Rural"
     27 "Enugu_Urban"
     28 "Enugu_Rural"
     29 "Fct_Urban"
     30 "Fct_Rural"
     31 "Gombe_Urban"
     32 "Gombe_Rural"
     33 "Imo_Urban"
     34 "Imo_Rural"
     35 "Jigawa_Urban"
     36 "Jigawa_Rural"
     37 "Kaduna_Urban"
     38 "Kaduna_Rural"
     39 "Kano_Urban"
     40 "Kano_Rural"
     41 "Katsina_Urban"
     42 "Katsina_Rural"
     43 "Kebbi_Urban"
     44 "Kebbi_Rural"
     45 "Kogi_Urban"
     46 "Kogi_Rural"
     47 "Kwara_Urban"
     48 "Kwara_Rural"
     49 "Lagos_Urban"
     50 "Lagos_Rural"
     51 "Nasarawa_Urban"
     52 "Nasarawa_Rural"
     53 "Niger_Urban"
     54 "Niger_Rural"
     55 "Ogun_Urban"
     56 "Ogun_Rural"
     57 "Ondo_Urban"
     58 "Ondo_Rural"
     59 "Osun_Urban"
     60 "Osun_Rural"
     61 "Oyo_Urban"
     62 "Oyo_Rural"
     63 "Plateau_Urban"
     64 "Plateau_Rural"
     65 "Rivers_Urban"
     66 "Rivers_Urban"
     67 "Rivers_Rural"
     68 "Rivers_Rural"
     69 "Sokoto_Urban"
     70 "Sokoto_Rural"
     71 "Taraba_Urban"
     72 "Taraba_Rural"
     73 "Yobe_Urban"
     74 "Yobe_Rural"
     75 "Zamfara_Urban"
     76 "Zamfara_Rural"
  /HV023   
      1 "Abia_Urban"
      2 "Abia_Rural"
      3 "Adamawa_Urban"
      4 "Adamawa_Rural"
      5 "Akwa Ibom_Urban"
      6 "Akwa Ibom_Rural"
      7 "Anambra_Urban"
      8 "Anambra_Rural"
      9 "Bauchi_Urban"
     10 "Bauchi_Rural"
     11 "Bayelsa_Urban"
     12 "Bayelsa_Rural"
     13 "Benue_Urban"
     14 "Benue_Rural"
     15 "Borno_Urban"
     16 "Borno_Rural"
     17 "Cross River_Urban"
     18 "Cross River_Rural"
     19 "Delta_Urban"
     20 "Delta_Rural"
     21 "Ebonyi_Urban"
     22 "Ebonyi_Rural"
     23 "Edo_Urban"
     24 "Edo_Rural"
     25 "Ekiti_Urban"
     26 "Ekiti_Rural"
     27 "Enugu_Urban"
     28 "Enugu_Rural"
     29 "Fct_Urban"
     30 "Fct_Rural"
     31 "Gombe_Urban"
     32 "Gombe_Rural"
     33 "Imo_Urban"
     34 "Imo_Rural"
     35 "Jigawa_Urban"
     36 "Jigawa_Rural"
     37 "Kaduna_Urban"
     38 "Kaduna_Rural"
     39 "Kano_Urban"
     40 "Kano_Rural"
     41 "Katsina_Urban"
     42 "Katsina_Rural"
     43 "Kebbi_Urban"
     44 "Kebbi_Rural"
     45 "Kogi_Urban"
     46 "Kogi_Rural"
     47 "Kwara_Urban"
     48 "Kwara_Rural"
     49 "Lagos_Urban"
     50 "Lagos_Rural"
     51 "Nasarawa_Urban"
     52 "Nasarawa_Rural"
     53 "Niger_Urban"
     54 "Niger_Rural"
     55 "Ogun_Urban"
     56 "Ogun_Rural"
     57 "Ondo_Urban"
     58 "Ondo_Rural"
     59 "Osun_Urban"
     60 "Osun_Rural"
     61 "Oyo_Urban"
     62 "Oyo_Rural"
     63 "Plateau_Urban"
     64 "Plateau_Rural"
     65 "Rivers_Urban"
     66 "Rivers_Urban"
     67 "Rivers_Rural"
     68 "Rivers_Rural"
     69 "Sokoto_Urban"
     70 "Sokoto_Rural"
     71 "Taraba_Urban"
     72 "Taraba_Rural"
     73 "Yobe_Urban"
     74 "Yobe_Rural"
     75 "Zamfara_Urban"
     76 "Zamfara_Rural"
  /HV024   
      1 "Sokoto"
      2 "Zamfara"
      3 "Katsina"
      4 "Jigawa"
      5 "Yobe"
      6 "Borno"
      7 "Adamawa"
      8 "Gombe"
      9 "Bauchi"
     10 "Kano"
     11 "Kaduna"
     12 "Kebbi"
     13 "Niger"
     14 "FCT"
     15 "Nasarawa"
     16 "Plateau"
     17 "Taraba"
     18 "Benue"
     19 "Kogi"
     20 "Kwara"
     21 "Oyo"
     22 "Osun"
     23 "Ekiti"
     24 "Ondo"
     25 "Edo"
     26 "Anambra"
     27 "Enugu"
     28 "Ebonyi"
     29 "Cross River"
     30 "Akwa Ibom"
     31 "Abia"
     32 "Imo"
     33 "Rivers"
     34 "Bayelsa"
     35 "Delta"
     36 "Lagos"
     37 "Ogun"
  /HV025   
      1 "Urban"
      2 "Rural"
  /HV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /HV027   
      0 "Not selected"
      1 "Men's survey"
      2 "Husband's survey"
  /HV042   
      0 "Not selected"
      1 "Selected"
  /HV045A  
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
  /HV045B  
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
  /HV045C  
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
      5 "Fulfulde"
      6 "Other"
  /HV046   
      0 "No"
      1 "Yes"
  /HV803   
     95 "95+"
     96 "2+ visits"
     97 "Inconsistent"
  /HV201   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Piped to neighbor"
     14 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE FROM SPRING"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     72 "Sachet water"
     96 "Other"
  /HV202   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Piped to neighbor"
     14 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE FROM SPRING"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     96 "Other"
  /HV201A  
      0 "No, not interrupted for a full day"
      1 "Yes, interrupted for a full day or more"
      8 "Don't know"
  /HV204   
    996 "On premises"
    998 "Don't know"
  /HV205   
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
  /HV206   
      0 "No"
      1 "Yes"
  /HV207   
      0 "No"
      1 "Yes"
  /HV208   
      0 "No"
      1 "Yes"
  /HV209   
      0 "No"
      1 "Yes"
  /HV210   
      0 "No"
      1 "Yes"
  /HV211   
      0 "No"
      1 "Yes"
  /HV212   
      0 "No"
      1 "Yes"
  /HV213   
     10 "NATURAL"
     11 "Earth/sand"
     12 "Dung"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm/bamboo"
     30 "FINISHED"
     31 "Parquet or polished wood"
     32 "Vinyl or asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "Other"
  /HV214   
     10 "NATURAL"
     11 "No walls"
     12 "Cane/palm/trunks"
     13 "Dirt"
     20 "RUDIMENTARY"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Uncovered adobe"
     24 "Plywood"
     25 "Cardboard"
     26 "Reused wood"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks/shingles"
     96 "Other"
  /HV215   
     10 "NATURAL"
     11 "No roof"
     12 "Thatch/palm leaf"
     13 "Grass"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     22 "Palm/bamboo"
     23 "Wood planks"
     24 "Cardboard"
     30 "FINISHED"
     31 "Metal/Zinc"
     32 "Wood"
     33 "Calamine/cement fiber"
     34 "Ceramic tiles"
     35 "Cement"
     36 "Roofing shingles"
     37 "Asbestos"
     96 "Other"
  /HV217   
      0 "No adults"
      1 "One adult"
      2 "Two adults, opposite sex"
      3 "Two adults, same sex"
      4 "Three+ related adults"
      5 "Unrelated adults"
  /HV219   
      1 "Male"
      2 "Female"
  /HV220   
     97 "97+"
     98 "Don't know"
  /HV221   
      0 "No"
      1 "Yes"
  /HV222   
      1 "Electric stove"
      2 "Solar cooker"
      3 "Liquefied petrolium gas (LPG)/cooking gas stove"
      4 "Piped natural gas stove"
      5 "Biogas stove"
      6 "Kerosene stove"
      7 "Manufactured solid fuel stove"
      8 "Traditional solid fuel stove"
      9 "Three stone stove/open fire"
     95 "No food cooked in household"
     96 "Other"
  /HV223   
      1 "Alcohol/ethanol"
      2 "Gasoline/diesel"
      3 "Kerosene/Paraffin"
      4 "Coal/lignite"
      5 "Charcoal"
      6 "Wood"
      7 "Straw/shrubs/grass"
      8 "Agricultural crop"
      9 "Animal dung/waste"
     10 "Processed biomass (pellets) or woodchips"
     11 "Garbage/plastic"
     12 "Sawdust"
     96 "Other"
  /HV225   
      0 "No"
      1 "Yes"
  /HV226   
      1 "Electricity"
      2 "Solar cooker"
      3 "LPG"
      4 "Natural gas"
      5 "Biogas"
      6 "Alcohol/ethanol"
      7 "Gasoline/diesel"
      8 "Kerosene/paraffin"
      9 "Coal/lignite"
     10 "Charcoal"
     11 "Wood"
     12 "Straw/shrubs/grass"
     13 "Agricultural crop"
     14 "Animal dung/waste"
     15 "Processed biomass (pellets) or woodchips"
     16 "Garbage/plastic"
     17 "Sawdust"
     95 "No food cooked in house"
     96 "Other"
  /HV227   
      0 "No"
      1 "Yes"
  /HV228   
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /HV235   
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /HV238   
     95 "10 or more households"
     98 "Don't know"
  /HV238A  
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /HV243A  
      0 "No"
      1 "Yes"
  /HV243B  
      0 "No"
      1 "Yes"
  /HV243C  
      0 "No"
      1 "Yes"
  /HV243D  
      0 "No"
      1 "Yes"
  /HV243E  
      0 "No"
      1 "Yes"
  /HV244   
      0 "No"
      1 "Yes"
  /HV245   
    950 "95 or more"
    998 "Unknown"
  /HV246   
      0 "No"
      1 "Yes"
  /HV246A  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246B  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246C  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246D  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246E  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246F  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246G  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246H  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246I  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246J  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246K  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV247   
      0 "No"
      1 "Yes"
  /HV270   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /HV270A  
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /HML1    
     98 "Don't know"
  /SHREGION
      1 "North Central"
      2 "North East"
      3 "North West"
      4 "South East"
      5 "South South"
      6 "South West"
  /SHBONNY 
      0 "No"
      1 "Yes"
  /SH116G  
      0 "No"
      1 "Yes"
  /SH116H  
      0 "No"
      1 "Yes"
  /SH116I  
      0 "No"
      1 "Yes"
  /SH116J  
      0 "No"
      1 "Yes"
  /SH116K  
      0 "No"
      1 "Yes"
  /SH116L  
      0 "No"
      1 "Yes"
  /SH116M  
      0 "No"
      1 "Yes"
  /SH116N  
      0 "No"
      1 "Yes"
  /SH116O  
      0 "No"
      1 "Yes"
  /SH117H  
      1 "Yes"
      0 "No"
  /SH117I  
      1 "Yes"
      0 "No"
  /SH119   
      1 "Yes"
      0 "No"
  /HV101   
      1 "Head"
      2 "Wife or husband"
      3 "Son/daughter"
      4 "Son/daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother/sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster/step child"
     12 "Not related"
     98 "Don't know"
  /HV102   
      0 "No"
      1 "Yes"
  /HV103   
      0 "No"
      1 "Yes"
  /HV104   
      1 "Male"
      2 "Female"
  /HV105   
     95 "95+"
     98 "Don't know"
  /HV117   
      0 "Not eligible"
      1 "Eligible"
  /HV120   
      0 "Not eligible"
      1 "Eligible"
  /HC16    
     97 "Inconsistent"
     98 "Don't know"
  /HC27    
      1 "Male"
      2 "Female"
  /HC30    
     97 "Inconsistent"
     98 "Don't know"
  /HC31    
   9997 "Inconsistent"
   9998 "Don't know"
  /HC33    
      0 "Month, year and day"
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HC51    
      0 "Not in household"
  /HC52    
      1 "Granted"
      2 "Refused"
      3 "Not present/other"
  /HC53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HC55    
      0 "Measured"
      3 "Not present/other"
      4 "Refused"
      6 "Other"
  /HC56    
    997 "Inconsistent"
  /HC57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HC58    
      0 "No"
      1 "Yes"
  /HC60    
    993 "Mother not de facto"
    994 "Incomplete woman's interview"
    995 "Not in household"
  /HC61    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HC62    
     98 "Don't know"
  /HC68    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /SB110B  
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Adult/parent not present"
      5 "Minor not present"
  /SB110E  
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Adult/parent not present"
      5 "Minor not present"
  /HML3    
      0 "Not seen"
      1 "Yes, seen"
  /HML4    
     96 "More than 3 years ago"
     98 "Don't know"
  /HML5    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HML6    
      0 "Not pretreated"
      1 "Pretreated, permanent treatment"
      2 "Pretreated, requiring future treatment"
      3 "Not pretreated, came with kit and treated at home"
      4 "Pretreated, treatment type not known"
      6 "Other"
      8 "Don't know"
  /HML7    
     11 "Permanet"
     12 "Olyset"
     13 "Iconlife"
     14 "Duranet"
     15 "Netprotect"
     16 "Basf Interceptor"
     17 "Yorkool"
     18 "Magnet"
     19 "Dawaplus 2.0"
     20 "Royal Security"
     21 "Royal Sentry"
     22 "Permanet 2.0"
     23 "Permanet 3.0"
     24 "Veeralin"
     25 "Interceptor G2"
     26 "Royal Guard"
     36 "Other/Don't know brand (LLIN)"
     96 "Other brand"
     98 "Don't know brand"
  /HML8    
      0 "No"
      1 "Yes"
      2 "Permanent/LLIN net"
      8 "Not sure"
  /HML9    
     95 "25+ months ago"
     96 "More than 3 years ago"
     98 "Don't know"
  /HML10   
      0 "No, don't know"
      1 "Yes"
  /HML11   
      5 "5+"
  /HML21   
      0 "No"
      1 "Yes"
      8 "Not sure (Don't know)"
  /HMLA    
      0 "No one"
  /HML22   
      0 "No"
      1 "Yes, mass distribution campaign"
      2 "Yes, antenatal care"
      3 "Yes, immunization visit"
  /HML23   
     10 "Government health facility"
     11 "Government health facility"
     20 "Private health facility"
     21 "Private health facility"
     30 "Other sources"
     31 "Pharmacy"
     32 "Shop/market"
     33 "CHW"
     34 "Religious institution"
     35 "School"
     96 "Other"
     98 "Don't know"
  /SH130   
      1 "No mosquitoes"
      2 "No malaria"
      3 "Too hot"
      4 "Don't like smell"
      5 "Feel 'closed in'"
      6 "Net too old/torn"
      7 "Net too dirty"
      8 "Net not available last night (washing)"
      9 "Usual users did not sleep here last night"
     10 "Net not needed last night"
     11 "Bed bugs"
     96 "Other"
     98 "Don't know"
     99 "Missing"
  /HML12   
      0 "Did not sleep under a net"
      1 "Only treated (ITN) nets"
      2 "Both treated (ITN) and untreated nets"
      3 "Only untreated nets"
  /HML13   
      0 "Did not sleep under net"
  /HML16   
     97 "97+"
     98 "Don't know"
  /HML17   
      0 "No data from Individual file"
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HML18   
      0 "Not pregnant, don't know"
      1 "Pregnant"
  /HML19   
      0 "No"
      1 "Yes"
  /HML20   
      0 "No"
      1 "Yes"
  /HML30   
      0 "Not in household"
  /HML31   
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Adult/parent not present"
      5 "Minor not present"
  /HML32   
      0 "Negative"
      1 "Positive"
      6 "Test undetermined"
      7 "Sample not found in lab database"
  /HML32A  
      0 "No"
      1 "Yes"
  /HML32B  
      0 "No"
      1 "Yes"
  /HML32C  
      0 "No"
      1 "Yes"
  /HML32D  
      0 "No"
      1 "Yes"
  /HML32E  
      0 "No"
      1 "Yes"
  /HML32F  
      0 "No"
      1 "Yes"
  /HML32G  
      0 "No"
      1 "Yes"
  /HML33   
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HML34   
   99993 "Sample damaged/insufficient/not found in lab"
   99994 "Not present"
   99995 "Refused"
   99996 "Other"
   '?    ' "Missing"
  /HML35   
      0 "Negative"
      1 "Positive"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HML37A  
      0 "No"
      1 "Yes"
  /HML37B  
      0 "No"
      1 "Yes"
  /HML37C  
      0 "No"
      1 "Yes"
  /HML37D  
      0 "No"
      1 "Yes"
  /HML37E  
      0 "No"
      1 "Yes"
  /HML37F  
      0 "No"
      1 "Yes"
  /HML37G  
      0 "No"
      1 "Yes"
  /HML37H  
      0 "No"
      1 "Yes"
  /HML37I  
      0 "No"
      1 "Yes"
  /HML37J  
      0 "No"
      1 "Yes"
  /HML37K  
      0 "No"
      1 "Yes"
  /HML37L  
      0 "No"
      1 "Yes"
  /HML37M  
      0 "No"
      1 "Yes"
  /HML38   
      0 "No"
      1 "Yes"
  /HML39   
      0 "Refused medicine"
      1 "Accepted medicine"
      6 "Other"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\NG81\NGPR81FL.sav'.
