DATA LIST FILE='C:\COUNTRIES\NG81\NGKR81FL.DAT' RECORDS=1
  /
  CASEID      1-15   (A)
  HIDXA      16-16  
  V000       17-19   (A)
  V001       20-25  
  V002       26-31  
  V003       32-34  
  V004       35-38  
  V005       39-46  
  V006       47-48  
  V007       49-52  
  V008       53-56  
  V008A      57-61  
  V009       62-63  
  V010       64-67  
  V011       68-71  
  V012       72-73  
  V013       74-74  
  V014       75-75  
  V015       76-76  
  V016       77-78  
  V021       79-82  
  V022       83-86  
  V023       87-88  
  V024       89-90  
  V025       91-91  
  V026       92-92  
  V027       93-93  
  V028       94-98  
  V029       99-101 
  V030      102-106 
  V031      107-111 
  V032      112-114 
  V034      115-116 
  V040      117-120 
  V042      121-121 
  V045A     122-124 
  V045B     125-127 
  V045C     128-130 
  V046      131-131 
  V047      132-136 
  V101      137-138 
  V102      139-139 
  V106      140-140 
  V107      141-142 
  V113      143-144 
  V115      145-147 
  V116      148-149 
  V119      150-150 
  V120      151-151 
  V121      152-152 
  V122      153-153 
  V123      154-154 
  V124      155-155 
  V125      156-156 
  V127      157-158 
  V128      159-160 
  V129      161-162 
  V130      163-164 
  V131      165-167 
  V133      168-169 
  V134      170-170 
  V135      171-171 
  V136      172-173 
  V137      174-175 
  V138      176-177 
  V139      178-179 
  V140      180-180 
  V141      181-181 
  V149      182-182 
  V150      183-184 
  V151      185-185 
  V152      186-187 
  V153      188-188 
  V155      189-189 
  V156      190-190 
  V157      191-191 
  V158      192-192 
  V159      193-193 
  V160      194-194 
  V161      195-196 
  V169A     197-197 
  V169C     198-198 
  V171A     199-199 
  V171B     200-200 
  V190      201-201 
  V191      202-209 
  V190A     210-210 
  V191A     211-218 
  ML101     219-219 
  V417      220-220 
  V418A     221-221 
  V419      222-222 
  V459      223-223 
  V460      224-224 
  V461      225-225 
  V468      226-226 
  BIDX      227-228 
  BORD      229-230 
  B0        231-231 
  B1        232-233 
  B2        234-237 
  B3        238-241 
  B4        242-242 
  B5        243-243 
  B6        244-246 
  B7        247-249 
  B8        250-251 
  B9        252-252 
  B10       253-253 
  B11       254-256 
  B12       257-259 
  B13       260-260 
  B15       261-261 
  B16       262-263 
  B17       264-265 
  B18       266-270 
  B19       271-273 
  V201      274-275 
  V202      276-277 
  V203      278-279 
  V204      280-281 
  V205      282-283 
  V206      284-285 
  V207      286-287 
  V208      288-288 
  V209      289-289 
  V210      290-290 
  V213      291-291 
  V214      292-293 
  V214A     294-296 
  V218      297-298 
  V219      299-300 
  V220      301-301 
  V222      302-304 
  V223      305-305 
  V224      306-307 
  V237      308-308 
  V238      309-309 
  MIDX      310-310 
  M2A       311-311 
  M2B       312-312 
  M2C       313-313 
  M2D       314-314 
  M2E       315-315 
  M2F       316-316 
  M2G       317-317 
  M2H       318-318 
  M2I       319-319 
  M2J       320-320 
  M2K       321-321 
  M2L       322-322 
  M2M       323-323 
  M2N       324-324 
  M13       325-326 
  M13A      327-329 
  M14       330-331 
  M49A      332-332 
  M49B      333-333 
  M49C      334-334 
  M49D      335-335 
  M49E      336-336 
  M49F      337-337 
  M49G      338-338 
  M49X      339-339 
  M49Z      340-340 
  M49Y      341-341 
  M57A      342-342 
  M57B      343-343 
  M57C      344-344 
  M57D      345-345 
  M57E      346-346 
  M57F      347-347 
  M57G      348-348 
  M57H      349-349 
  M57I      350-350 
  M57J      351-351 
  M57K      352-352 
  M57L      353-353 
  M57M      354-354 
  M57N      355-355 
  M57O      356-356 
  M57P      357-357 
  M57Q      358-358 
  M57R      359-359 
  M57NA     360-360 
  M57NB     361-361 
  M57NC     362-362 
  M57ND     363-363 
  M57NE     364-364 
  M57S      365-365 
  M57T      366-366 
  M57U      367-367 
  M57V      368-368 
  M57X      369-369 
  ML1       370-371 
  ML2       372-372 
  H22       373-373 
  H31       374-374 
  H32A      375-375 
  H32B      376-376 
  H32C      377-377 
  H32D      378-378 
  H32E      379-379 
  H32F      380-380 
  H32G      381-381 
  H32H      382-382 
  H32I      383-383 
  H32J      384-384 
  H32K      385-385 
  H32L      386-386 
  H32M      387-387 
  H32N      388-388 
  H32O      389-389 
  H32P      390-390 
  H32Q      391-391 
  H32R      392-392 
  H32NA     393-393 
  H32NB     394-394 
  H32NC     395-395 
  H32ND     396-396 
  H32NE     397-397 
  H32S      398-398 
  H32T      399-399 
  H32U      400-400 
  H32V      401-401 
  H32W      402-402 
  H32X      403-403 
  H32Y      404-404 
  H32Z      405-405 
  H46A      406-407 
  H46B      408-409 
  H47       410-410 
  H71       411-411 
  HWIDX     412-412 
  HW1       413-414 
  HW16      415-416 
  HW17      417-418 
  HW18      419-420 
  HW19      421-424 
  HW51      425-426 
  HW52      427-427 
  HW53      428-430 
  HW55      431-431 
  HW56      432-435 
  HW57      436-436 
  HW58      437-437 
  IDXML     438-438 
  ML0       439-439 
  ML11      440-440 
  ML12      441-441 
  ML13A     442-442 
  ML13B     443-443 
  ML13C     444-444 
  ML13D     445-445 
  ML13DA    446-446 
  ML13E     447-447 
  ML13AA    448-448 
  ML13AB    449-449 
  ML13F     450-450 
  ML13G     451-451 
  ML13H     452-452 
  ML13I     453-453 
  ML13J     454-454 
  ML13K     455-455 
  ML13L     456-456 
  ML13M     457-457 
  ML13N     458-458 
  ML13O     459-459 
  ML13P     460-460 
  ML13X     461-461 
  ML13Y     462-462 
  ML13Z     463-463 
  ML14A     464-464 
  ML14B     465-465 
  ML14Y     466-466 
  ML14Z     467-467 
  ML15A     468-468 
  ML15B     469-469 
  ML15C     470-470 
  ML16A     471-471 
  ML16B     472-472 
  ML16C     473-473 
  ML17A     474-474 
  ML17B     475-475 
  ML17C     476-476 
  ML18A     477-477 
  ML18B     478-478 
  ML18C     479-479 
  ML19A     480-480 
  ML19B     481-481 
  ML19C     482-482 
  ML19D     483-483 
  ML19E     484-484 
  ML19F     485-485 
  ML19X     486-486 
  ML19Y     487-487 
  ML19Z     488-488 
  ML20A     489-489 
  ML20B     490-490 
  ML20C     491-491 
  ML21A     492-492 
  ML21B     493-493 
  ML21C     494-494 
  ML22A     495-495 
  ML22B     496-496 
  ML22C     497-497 
  ML23A     498-498 
  ML23B     499-499 
  ML23C     500-500 
  ML24C     501-501 
  ML25A     502-502 
  ML501     503-503 
  ML501A    504-504 
  ML501B    505-505 
  ML501C    506-506 
  ML501D    507-507 
  ML501E    508-508 
  ML501F    509-509 
  ML501G    510-510 
  ML501H    511-511 
  ML501I    512-512 
  ML501J    513-513 
  ML501K    514-514 
  ML501X    515-515 
  ML501Z    516-516 
  ML503     517-517 
  ML503A    518-518 
  ML503B    519-519 
  ML503C    520-520 
  ML503D    521-521 
  ML503E    522-522 
  ML503F    523-523 
  ML503G    524-524 
  ML503H    525-525 
  ML503I    526-526 
  ML503J    527-527 
  ML503K    528-528 
  ML503X    529-529 
  ML503Z    530-530 
  ML505     531-531 
  ML506     532-532 
  ML507     533-533 
  ML508     534-534 
  ML509     535-535 
  ML510     536-536 
  ML511     537-537 
  ML512     538-538 
  ML513     539-539 
  ML514     540-540 
  S512A     541-541 
  SLGA      542-544 
  SREGION   545-545 
  SBONNY    546-546 
  S104A     547-547 
  S104B     548-548 
  S211      549-550 
  IDX95     551-551 
  S411A     552-552 
  S415A     553-553 
 .
VARIABLE LABELS
   CASEID   "Case Identification"
  /HIDXA    "Index to birth history"
  /V000     "Country code and phase"
  /V001     "Cluster number"
  /V002     "Household number"
  /V003     "Respondent's line number"
  /V004     "Ultimate area unit"
  /V005     "Women's individual sample weight (6 decimals)"
  /V006     "Month of interview"
  /V007     "Year of interview"
  /V008     "Date of interview (CMC)"
  /V008A    "Date of interview Century Day Code (CDC)"
  /V009     "Respondent's month of birth"
  /V010     "Respondent's year of birth"
  /V011     "Date of birth (CMC)"
  /V012     "Respondent's current age"
  /V013     "Age in 5-year groups"
  /V014     "Completeness of age information"
  /V015     "Result of individual interview"
  /V016     "Day of interview"
  /V021     "Primary sampling unit"
  /V022     "Sample strata for sampling errors"
  /V023     "Stratification used in sample design"
  /V024     "Region"
  /V025     "Type of place of residence"
  /V026     "NA - De facto place of residence"
  /V027     "Number of visits"
  /V028     "Interviewer identification"
  /V029     "NA - Keyer identification"
  /V030     "Field supervisor"
  /V031     "NA - Field editor"
  /V032     "NA - Office editor"
  /V034     "NA - Line number of husband"
  /V040     "Cluster altitude in meters"
  /V042     "Household selected for hemoglobin"
  /V045A    "Language of questionnaire"
  /V045B    "Language of interview"
  /V045C    "Native language of respondent"
  /V046     "Translator used"
  /V047     "Team number"
  /V101     "Region"
  /V102     "Type of place of residence"
  /V106     "Highest educational level"
  /V107     "Highest year of education"
  /V113     "Source of drinking water"
  /V115     "Time to get to water source"
  /V116     "Type of toilet facility"
  /V119     "Household has: electricity"
  /V120     "Household has: radio"
  /V121     "Household has: television"
  /V122     "Household has: refrigerator"
  /V123     "Household has: bicycle"
  /V124     "Household has: motorcycle/scooter"
  /V125     "Household has: car/truck"
  /V127     "Main floor material"
  /V128     "Main wall material"
  /V129     "Main roof material"
  /V130     "Religion"
  /V131     "Ethnicity"
  /V133     "Education in single years"
  /V134     "NA - De facto place of residence"
  /V135     "Usual resident or visitor"
  /V136     "Number of household members (listed)"
  /V137     "Number of children 5 and under in household (de jure)"
  /V138     "Number of eligible women in household (de facto)"
  /V139     "De jure region of residence"
  /V140     "De jure type of place of residence"
  /V141     "NA - De jure place of residence"
  /V149     "Educational attainment"
  /V150     "Relationship to household head"
  /V151     "Sex of household head"
  /V152     "Age of household head"
  /V153     "Household has: telephone (land-line)"
  /V155     "Literacy"
  /V156     "NA - Ever participated in a literacy program outside of primary"
  /V157     "Frequency of reading newspaper or magazine"
  /V158     "Frequency of listening to radio"
  /V159     "Frequency of watching television"
  /V160     "Toilet facilities shared with other households"
  /V161     "Type of cooking fuel"
  /V169A    "Owns a mobile telephone"
  /V169C    "Is respondent's mobile phone a smart phone"
  /V171A    "Use of internet"
  /V171B    "Frequency of using internet last month"
  /V190     "Wealth index combined"
  /V191     "Wealth index factor score combined (5 decimals)"
  /V190A    "Wealth index for urban/rural"
  /V191A    "Wealth index factor score for urban/rural (5 decimals)"
  /ML101    "Type of mosquito bed net(s) slept under last night"
  /V417     "Entries in pregnancy and postnatal care roster"
  /V418A    "Entries in child health roster"
  /V419     "Entries in height/weight roster"
  /V459     "Have mosquito bed net for sleeping (from household questionnaire)"
  /V460     "Children under 5 slept under mosquito bed net last night (household questionnaire)"
  /V461     "Respondent slept under mosquito bed net"
  /V468     "Record for Last Birth"
  /BIDX     "Birth column number"
  /BORD     "Birth order number"
  /B0       "Child is twin"
  /B1       "Month of birth"
  /B2       "Year of birth"
  /B3       "Date of birth (CMC)"
  /B4       "Sex of child"
  /B5       "Child is alive"
  /B6       "NA - Age at death"
  /B7       "NA - Age at death (months, imputed)"
  /B8       "Current age of child"
  /B9       "Child lives with whom"
  /B10      "Completeness of information"
  /B11      "Preceding birth interval (months)"
  /B12      "Succeeding birth interval (months)"
  /B13      "NA - Flag for age at death"
  /B15      "Live birth between births"
  /B16      "Child's line number in household"
  /B17      "Day of birth"
  /B18      "Century Day Code of birth (CDC)"
  /B19      "Current age of child in months (months since birth for dead children)"
  /V201     "Total children ever born"
  /V202     "Sons at home"
  /V203     "Daughters at home"
  /V204     "Sons elsewhere"
  /V205     "Daughters elsewhere"
  /V206     "Sons who have died"
  /V207     "Daughters who have died"
  /V208     "Births in last five years"
  /V209     "Births in past year"
  /V210     "Births in month of interview"
  /V213     "Currently pregnant"
  /V214     "Duration of current pregnancy in months"
  /V214A    "Duration of current pregnancy original"
  /V218     "Number of living children"
  /V219     "Living children + current pregnancy"
  /V220     "Living children + current pregnancy (grouped)"
  /V222     "Last birth to interview (months)"
  /V223     "Completeness of current pregnancy information"
  /V224     "Entries in birth history"
  /V237     "Birth between last and interview"
  /V238     "Births in last three years"
  /MIDX     "Index to Birth History"
  /M2A      "Prenatal: doctor"
  /M2B      "Prenatal: nurse/midwife"
  /M2C      "Prenatal: auxiliary midwife"
  /M2D      "Prenatal: government health community extension health worker"
  /M2E      "NA - Prenatal: CS health professional"
  /M2F      "NA - Prenatal: CS health professional"
  /M2G      "Prenatal: traditional birth attendant"
  /M2H      "Prenatal: Community health worker/field worker"
  /M2I      "NA - Prenatal: CS other person"
  /M2J      "NA - Prenatal: CS other person"
  /M2K      "Prenatal: other"
  /M2L      "NA - Prenatal: CS other"
  /M2M      "NA - Prenatal: CS other"
  /M2N      "Prenatal: no one"
  /M13      "Timing of 1st antenatal check (months)"
  /M13A     "Timing of 1st antenatal check (original)"
  /M14      "Number of antenatal visits during pregnancy"
  /M49A     "During pregnancy took: SP/fansidar for malaria"
  /M49B     "NA - During pregnancy took: chloroquine for malaria"
  /M49C     "NA - During pregnancy took: CS drug for malaria"
  /M49D     "NA - During pregnancy took: CS drug for malaria"
  /M49E     "NA - During pregnancy took: CS drug for malaria"
  /M49F     "NA - During pregnancy took: CS drug for malaria"
  /M49G     "NA - During pregnancy took: CS drug for malaria"
  /M49X     "NA - During pregnancy took: other drug for malaria"
  /M49Z     "NA - During pregnancy took: don't know"
  /M49Y     "NA - During pregnancy took: no drug for malaria"
  /M57A     "Antenatal care: respondent's home"
  /M57B     "Antenatal care: other home"
  /M57C     "NA - Antenatal care: CS home"
  /M57D     "NA - Antenatal care: CS home"
  /M57E     "Antenatal care: government hospital"
  /M57F     "Antenatal care: government health center"
  /M57G     "Antenatal care: government health post"
  /M57H     "Antenatal care: other public sector"
  /M57I     "NA - Antenatal care: CS public health"
  /M57J     "NA - Antenatal care: CS public health"
  /M57K     "NA - Antenatal care: CS public health"
  /M57L     "NA - Antenatal care: CS public health"
  /M57M     "Antenatal care: private hospital"
  /M57N     "Antenatal care: private clinic"
  /M57O     "Antenatal care: other private medical sector"
  /M57P     "NA - Antenatal care: CS private medical"
  /M57Q     "NA - Antenatal care: CS private medical"
  /M57R     "NA - Antenatal care: CS private medical"
  /M57NA    "Antenatal care: NGO hospital"
  /M57NB    "Antenatal care: NGO clinic"
  /M57NC    "Antenatal care: other NGO medical sector"
  /M57ND    "NA - Antenatal care: NGO medical"
  /M57NE    "NA - Antenatal care: NGO medical"
  /M57S     "NA - Antenatal care: CS other"
  /M57T     "NA - Antenatal care: CS other"
  /M57U     "NA - Antenatal care: CS other"
  /M57V     "NA - Antenatal care: CS other"
  /M57X     "Antenatal care: other"
  /ML1      "Number of times took fansidar during pregnancy"
  /ML2      "Source of antimalarial during pregnancy"
  /H22      "Had fever in last two weeks"
  /H31      "NA - Had cough in last two weeks"
  /H32A     "Fever/cough: government hospital"
  /H32B     "Fever/cough: government health center"
  /H32C     "Fever/cough: government health post"
  /H32D     "Fever/cough: government mobile clinic"
  /H32E     "Fever/cough: government community health worker/fieldworker"
  /H32F     "Fever/cough: other public sector"
  /H32G     "NA - Fever/cough: CS public sector"
  /H32H     "NA - Fever/cough: CS public sector"
  /H32I     "NA - Fever/cough: CS public sector"
  /H32J     "Fever/cough: private hospital"
  /H32K     "Fever/cough: private pharmacy"
  /H32L     "Fever/cough: private doctor"
  /H32M     "Fever/cough: private clinic"
  /H32N     "Fever/cough: private mobile clinic"
  /H32O     "Fever/cough: private community health worker/fieldworker"
  /H32P     "Fever/cough: other private medical sector"
  /H32Q     "NA - Fever/cough: CS private medical"
  /H32R     "NA - Fever/cough: CS private medical"
  /H32NA    "Fever/cough: NGO hospital"
  /H32NB    "Fever/cough: NGO clinic"
  /H32NC    "Fever/cough: other NGO sector"
  /H32ND    "NA - Fever/cough: CS NGO"
  /H32NE    "NA - Fever/cough: CS NGO"
  /H32S     "Fever/cough: chemist shop/PPMV"
  /H32T     "Fever/cough: traditional practitioner"
  /H32U     "Fever/cough: market"
  /H32V     "Fever/cough: itinerant drug seller"
  /H32W     "Fever/cough: community-oriented resource person"
  /H32X     "Fever/cough: other"
  /H32Y     "Fever/cough: no treatment"
  /H32Z     "Fever/cough: medical treatment"
  /H46A     "Place first sought treatment for fever"
  /H46B     "Number of days after fever began sought advice or treatment"
  /H47      "Blood taken from child's finger/heel for testing"
  /H71      "Was respondent told that child had malaria"
  /HWIDX    "Index to Birth History"
  /HW1      "Child's age in months"
  /HW16     "Day of birth of child"
  /HW17     "Date measured (day)"
  /HW18     "Date measured (month)"
  /HW19     "Date measured (year)"
  /HW51     "Line number of parent/caretaker"
  /HW52     "Read consent statement - hemoglobin"
  /HW53     "Hemoglobin level (g/dl - 1 decimal)"
  /HW55     "Result of measurement - hemoglobin"
  /HW56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HW57     "Anemia level"
  /HW58     "NA - Agrees to referral - anemia"
  /IDXML    "Index to Birth History"
  /ML0      "Type of mosquito bed net(s) child slept under last night"
  /ML11     "NA - Child has fever/cough now"
  /ML12     "NA - Child has had convulsions in last 2 weeks"
  /ML13A    "Fansidar taken for fever"
  /ML13B    "Chloroquine taken for fever"
  /ML13C    "Amodiaquine taken for fever"
  /ML13D    "Quinine taken for fever"
  /ML13DA   "Quinine injection/IV taken for fever"
  /ML13E    "Combination with artemisinin taken for fever"
  /ML13AA   "Artesunate rectal taken for fever"
  /ML13AB   "Artesunate injection/IV taken for fever"
  /ML13F    "NA - CS antimalarial taken for fever"
  /ML13G    "NA - CS antimalarial taken for fever"
  /ML13H    "Other antimalarial taken for fever"
  /ML13I    "Antibiotic pill/syrup taken for fever"
  /ML13J    "Antibiotic injection taken for fever"
  /ML13K    "Aspirin taken for fever"
  /ML13L    "Acetaminophen/paracetamol/panadol taken for fever"
  /ML13M    "Ibuprofen taken for fever"
  /ML13N    "Amoxicillin taken for fever"
  /ML13O    "Cotrimoxazole taken for fever"
  /ML13P    "NA - CS other taken for fever"
  /ML13X    "Other taken for fever"
  /ML13Y    "Nothing taken and didn't seek treatment for fever/cough"
  /ML13Z    "Don't know if or what was taken for fever"
  /ML14A    "NA - Injection given for fever/convulsion"
  /ML14B    "NA - Suppository given for fever/convulsion"
  /ML14Y    "NA - No suppository or injection given for fever/convulsion"
  /ML14Z    "NA - Don't know if suppository or injection given for fever/convulsion"
  /ML15A    "NA - Timing of start of fansidar"
  /ML15B    "NA - Number of days child took fansidar"
  /ML15C    "NA - First source for fansidar"
  /ML16A    "NA - Timing of start of chloroquine"
  /ML16B    "NA - Number of days child took chloroquine"
  /ML16C    "NA - First source for chloroquine"
  /ML17A    "NA - Timing of start of amodiaquine"
  /ML17B    "NA - Number of days child took amodiaquine"
  /ML17C    "NA - First source for amodiaquine"
  /ML18A    "NA - Timing of start of quinine"
  /ML18B    "NA - Number of days child took quinine"
  /ML18C    "NA - First source for quinine"
  /ML19A    "NA - For fever/convulsion: consulted traditional healer"
  /ML19B    "NA - For fever/convulsion: gave tepid sponging"
  /ML19C    "NA - For fever/convulsion: gave herbs"
  /ML19D    "NA - For fever/convulsion: CS"
  /ML19E    "NA - For fever/convulsion: CS"
  /ML19F    "NA - For fever/convulsion: CS"
  /ML19X    "NA - For fever/convulsion: other"
  /ML19Y    "NA - For fever/convulsion: gave/did nothing"
  /ML19Z    "NA - For fever/convulsion: don't know if something else was done"
  /ML20A    "Timing of start of combination with artemisinin"
  /ML20B    "NA - Number of days child took combination with artemisinin"
  /ML20C    "NA - First source for combination with artemisinin"
  /ML21A    "NA - Timing of start of CS antimalarial use"
  /ML21B    "NA - Number of days child took CS antimalarial"
  /ML21C    "NA - First source for CS antimalarial"
  /ML22A    "NA - Timing of start of CS antimalarial use"
  /ML22B    "NA - Number of days child took CS antimalarial"
  /ML22C    "NA - First source for CS antimalarial"
  /ML23A    "NA - Timing of start of other anti-malarial use"
  /ML23B    "NA - Number of days child took other anti-malarial"
  /ML23C    "NA - First source for other anti-malarial"
  /ML24C    "NA - First source for antibiotic pill/syrup"
  /ML25A    "NA - Timing of start of artesunate"
  /ML501    "Last six months heard/seen malaria messages"
  /ML501A   "Malaria messages were heard/seen: radio"
  /ML501B   "Malaria messages were heard/seen: television"
  /ML501C   "Malaria messages were heard/seen: poster/billboard"
  /ML501D   "Malaria messages were heard/seen: newspaper/magazine"
  /ML501E   "Malaria messages were heard/seen: leaflet/brochure"
  /ML501F   "Malaria messages were heard/seen: healthcare provider"
  /ML501G   "Malaria messages were heard/seen: community health worker"
  /ML501H   "Malaria messages were heard/seen: social media"
  /ML501I   "Malaria messages were heard/seen: town announcer"
  /ML501J   "Malaria messages were heard/seen: inter-personal communication agent/community volunteer"
  /ML501K   "Malaria messages were heard/seen: family/friends"
  /ML501X   "Malaria messages were heard/seen: other"
  /ML501Z   "Malaria messages were heard/seen: don't remember"
  /ML503    "Are there ways to avoid getting malaria"
  /ML503A   "Malaria can be prevented by: sleep inside a mosquito net"
  /ML503B   "Malaria can be prevented by: sleep inside an insecticide-treated mosquito net"
  /ML503C   "Malaria can be prevented by: use mosquito repellent or coil"
  /ML503D   "Malaria can be prevented by: take preventive medications"
  /ML503E   "Malaria can be prevented by: spray house with insecticide"
  /ML503F   "Malaria can be prevented by: fill in stagnant waters (puddles)"
  /ML503G   "Malaria can be prevented by: keep surroundings clean"
  /ML503H   "Malaria can be prevented by: put mosquito screen on windows"
  /ML503I   "NA - Malaria can be prevented by: CS"
  /ML503J   "NA - Malaria can be prevented by: CS"
  /ML503K   "NA - Malaria can be prevented by: CS"
  /ML503X   "Malaria can be prevented by: other"
  /ML503Z   "Malaria can be prevented by: don't know"
  /ML505    "Agree/disagree with: people in community get malaria in rainy season"
  /ML506    "Agree/disagree with: when child has fever worry it is malaria"
  /ML507    "Agree/disagree with: getting malaria not a problem as can be treated"
  /ML508    "Agree/disagree with: only weak children can die from malaria"
  /ML509    "Agree/disagree with: sleep inside net when there are lots of mosquitoes"
  /ML510    "Agree/disagree with: sleep inside net when there are few mosquitoes"
  /ML511    "Agree/disagree with: don't like sleep inside a net when is too warm"
  /ML512    "Agree/disagree with: if child has fever best to give medicine available at home"
  /ML513    "Agree/disagree with: people take children to health provider same day or next day develop fever"
  /ML514    "Agree/disagree with: people who have nets usually sleep under every night"
  /S512A    "Agree/disagree with: important children take full dose of medicine they are prescribed for malaria"
  /SLGA     "Local government area"
  /SREGION  "Region"
  /SBONNY   "Bonny State"
  /S104A    "Had informal education"
  /S104B    "Type of informal education"
  /S211     "Number of births 2016-2021"
  /IDX95    "Index to Birth History"
  /S411A    "Referred to higher level of care"
  /S415A    "Fever went away after took ACT"
 .
MISSING VALUE
   V026     (9)
  /V027     (9)
  /V029     (999)
  /V034     (99)
  /V040     (9999)
  /V106     (9)
  /V107     (99)
  /V113     (99)
  /V115     (999)
  /V116     (99)
  /V119     (9)
  /V120     (9)
  /V121     (9)
  /V122     (9)
  /V123     (9)
  /V124     (9)
  /V125     (9)
  /V127     (99)
  /V128     (99)
  /V129     (99)
  /V130     (99)
  /V131     (999)
  /V133     (99)
  /V134     (9)
  /V135     (9)
  /V139     (99)
  /V140     (9)
  /V141     (9)
  /V149     (9)
  /V150     (99)
  /V152     (99)
  /V153     (9)
  /V155     (9)
  /V156     (9)
  /V157     (9)
  /V158     (9)
  /V159     (9)
  /V160     (9)
  /V161     (99)
  /V169A    (9)
  /V169C    (9)
  /V171A    (9)
  /V171B    (9)
  /ML101    (9)
  /V459     (9)
  /V460     (9)
  /V461     (9)
  /B6       (999)
  /B9       (9)
  /B15      (9)
  /B16      (99)
  /V214A    (999)
  /V237     (9)
  /M2A      (9)
  /M2B      (9)
  /M2C      (9)
  /M2D      (9)
  /M2E      (9)
  /M2F      (9)
  /M2G      (9)
  /M2H      (9)
  /M2I      (9)
  /M2J      (9)
  /M2K      (9)
  /M2L      (9)
  /M2M      (9)
  /M2N      (9)
  /M13      (99)
  /M13A     (999)
  /M14      (99)
  /M49A     (9)
  /M49B     (9)
  /M49C     (9)
  /M49D     (9)
  /M49E     (9)
  /M49F     (9)
  /M49G     (9)
  /M49X     (9)
  /M49Z     (9)
  /M49Y     (9)
  /M57A     (9)
  /M57B     (9)
  /M57C     (9)
  /M57D     (9)
  /M57E     (9)
  /M57F     (9)
  /M57G     (9)
  /M57H     (9)
  /M57I     (9)
  /M57J     (9)
  /M57K     (9)
  /M57L     (9)
  /M57M     (9)
  /M57N     (9)
  /M57O     (9)
  /M57P     (9)
  /M57Q     (9)
  /M57R     (9)
  /M57NA    (9)
  /M57NB    (9)
  /M57NC    (9)
  /M57ND    (9)
  /M57NE    (9)
  /M57S     (9)
  /M57T     (9)
  /M57U     (9)
  /M57V     (9)
  /M57X     (9)
  /ML1      (99)
  /ML2      (9)
  /H22      (9)
  /H31      (9)
  /H32A     (9)
  /H32B     (9)
  /H32C     (9)
  /H32D     (9)
  /H32E     (9)
  /H32F     (9)
  /H32G     (9)
  /H32H     (9)
  /H32I     (9)
  /H32J     (9)
  /H32K     (9)
  /H32L     (9)
  /H32M     (9)
  /H32N     (9)
  /H32O     (9)
  /H32P     (9)
  /H32Q     (9)
  /H32R     (9)
  /H32NA    (9)
  /H32NB    (9)
  /H32NC    (9)
  /H32ND    (9)
  /H32NE    (9)
  /H32S     (9)
  /H32T     (9)
  /H32U     (9)
  /H32V     (9)
  /H32W     (9)
  /H32X     (9)
  /H32Y     (9)
  /H32Z     (9)
  /H46A     (99)
  /H46B     (99)
  /H47      (9)
  /HW16     (99)
  /HW51     (99)
  /HW52     (9)
  /HW53     (999)
  /HW55     (9)
  /HW56     (9999)
  /HW57     (9)
  /HW58     (9)
  /ML0      (9)
  /ML11     (9)
  /ML12     (9)
  /ML13A    (9)
  /ML13B    (9)
  /ML13C    (9)
  /ML13D    (9)
  /ML13DA   (9)
  /ML13E    (9)
  /ML13AA   (9)
  /ML13AB   (9)
  /ML13F    (9)
  /ML13G    (9)
  /ML13H    (9)
  /ML13I    (9)
  /ML13J    (9)
  /ML13K    (9)
  /ML13L    (9)
  /ML13M    (9)
  /ML13N    (9)
  /ML13O    (9)
  /ML13P    (9)
  /ML13X    (9)
  /ML13Y    (9)
  /ML13Z    (9)
  /ML14A    (9)
  /ML14B    (9)
  /ML14Y    (9)
  /ML14Z    (9)
  /ML15A    (9)
  /ML15B    (9)
  /ML15C    (9)
  /ML16A    (9)
  /ML16B    (9)
  /ML16C    (9)
  /ML17A    (9)
  /ML17B    (9)
  /ML17C    (9)
  /ML18A    (9)
  /ML18B    (9)
  /ML18C    (9)
  /ML19A    (9)
  /ML19B    (9)
  /ML19C    (9)
  /ML19D    (9)
  /ML19E    (9)
  /ML19F    (9)
  /ML19X    (9)
  /ML19Y    (9)
  /ML19Z    (9)
  /ML20A    (9)
  /ML20B    (9)
  /ML20C    (9)
  /ML21A    (9)
  /ML21B    (9)
  /ML21C    (9)
  /ML22A    (9)
  /ML22B    (9)
  /ML22C    (9)
  /ML23A    (9)
  /ML23B    (9)
  /ML23C    (9)
  /ML24C    (9)
  /ML25A    (9)
  /ML501    (9)
  /ML501A   (9)
  /ML501B   (9)
  /ML501C   (9)
  /ML501D   (9)
  /ML501E   (9)
  /ML501F   (9)
  /ML501G   (9)
  /ML501H   (9)
  /ML501I   (9)
  /ML501J   (9)
  /ML501K   (9)
  /ML501X   (9)
  /ML501Z   (9)
  /ML503    (9)
  /ML503A   (9)
  /ML503B   (9)
  /ML503C   (9)
  /ML503D   (9)
  /ML503E   (9)
  /ML503F   (9)
  /ML503G   (9)
  /ML503H   (9)
  /ML503I   (9)
  /ML503J   (9)
  /ML503K   (9)
  /ML503X   (9)
  /ML503Z   (9)
  /ML505    (9)
  /ML506    (9)
  /ML507    (9)
  /ML508    (9)
  /ML509    (9)
  /ML510    (9)
  /ML511    (9)
  /ML512    (9)
  /ML513    (9)
  /ML514    (9)
  /S512A    (9)
  /S104A    (9)
  /S411A    (9)
  /S415A    (9)
 .
VALUE LABELS
   V013    
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
  /V014    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /V015    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partially completed"
      6 "Respondent incapacitated"
      7 "Other"
  /V022    
      1 "Abia_Urban"
      2 "Abia_Rural"
      3 "Adamawa_Urban"
      4 "Adamawa_Rural"
      5 "Akwa Ibom_Urban"
      6 "Akwa Ibom_Rural"
      7 "Anambra_Urban"
      8 "Anambra_Rural"
      9 "Bauchi_Urban"
     10 "Bauchi_Rural"
     11 "Bayelsa_Urban"
     12 "Bayelsa_Rural"
     13 "Benue_Urban"
     14 "Benue_Rural"
     15 "Borno_Urban"
     16 "Borno_Rural"
     17 "Cross River_Urban"
     18 "Cross River_Rural"
     19 "Delta_Urban"
     20 "Delta_Rural"
     21 "Ebonyi_Urban"
     22 "Ebonyi_Rural"
     23 "Edo_Urban"
     24 "Edo_Rural"
     25 "Ekiti_Urban"
     26 "Ekiti_Rural"
     27 "Enugu_Urban"
     28 "Enugu_Rural"
     29 "Fct_Urban"
     30 "Fct_Rural"
     31 "Gombe_Urban"
     32 "Gombe_Rural"
     33 "Imo_Urban"
     34 "Imo_Rural"
     35 "Jigawa_Urban"
     36 "Jigawa_Rural"
     37 "Kaduna_Urban"
     38 "Kaduna_Rural"
     39 "Kano_Urban"
     40 "Kano_Rural"
     41 "Katsina_Urban"
     42 "Katsina_Rural"
     43 "Kebbi_Urban"
     44 "Kebbi_Rural"
     45 "Kogi_Urban"
     46 "Kogi_Rural"
     47 "Kwara_Urban"
     48 "Kwara_Rural"
     49 "Lagos_Urban"
     50 "Lagos_Rural"
     51 "Nasarawa_Urban"
     52 "Nasarawa_Rural"
     53 "Niger_Urban"
     54 "Niger_Rural"
     55 "Ogun_Urban"
     56 "Ogun_Rural"
     57 "Ondo_Urban"
     58 "Ondo_Rural"
     59 "Osun_Urban"
     60 "Osun_Rural"
     61 "Oyo_Urban"
     62 "Oyo_Rural"
     63 "Plateau_Urban"
     64 "Plateau_Rural"
     65 "Rivers_Urban"
     66 "Rivers_Urban"
     67 "Rivers_Rural"
     68 "Rivers_Rural"
     69 "Sokoto_Urban"
     70 "Sokoto_Rural"
     71 "Taraba_Urban"
     72 "Taraba_Rural"
     73 "Yobe_Urban"
     74 "Yobe_Rural"
     75 "Zamfara_Urban"
     76 "Zamfara_Rural"
  /V023    
      1 "Abia_Urban"
      2 "Abia_Rural"
      3 "Adamawa_Urban"
      4 "Adamawa_Rural"
      5 "Akwa Ibom_Urban"
      6 "Akwa Ibom_Rural"
      7 "Anambra_Urban"
      8 "Anambra_Rural"
      9 "Bauchi_Urban"
     10 "Bauchi_Rural"
     11 "Bayelsa_Urban"
     12 "Bayelsa_Rural"
     13 "Benue_Urban"
     14 "Benue_Rural"
     15 "Borno_Urban"
     16 "Borno_Rural"
     17 "Cross River_Urban"
     18 "Cross River_Rural"
     19 "Delta_Urban"
     20 "Delta_Rural"
     21 "Ebonyi_Urban"
     22 "Ebonyi_Rural"
     23 "Edo_Urban"
     24 "Edo_Rural"
     25 "Ekiti_Urban"
     26 "Ekiti_Rural"
     27 "Enugu_Urban"
     28 "Enugu_Rural"
     29 "Fct_Urban"
     30 "Fct_Rural"
     31 "Gombe_Urban"
     32 "Gombe_Rural"
     33 "Imo_Urban"
     34 "Imo_Rural"
     35 "Jigawa_Urban"
     36 "Jigawa_Rural"
     37 "Kaduna_Urban"
     38 "Kaduna_Rural"
     39 "Kano_Urban"
     40 "Kano_Rural"
     41 "Katsina_Urban"
     42 "Katsina_Rural"
     43 "Kebbi_Urban"
     44 "Kebbi_Rural"
     45 "Kogi_Urban"
     46 "Kogi_Rural"
     47 "Kwara_Urban"
     48 "Kwara_Rural"
     49 "Lagos_Urban"
     50 "Lagos_Rural"
     51 "Nasarawa_Urban"
     52 "Nasarawa_Rural"
     53 "Niger_Urban"
     54 "Niger_Rural"
     55 "Ogun_Urban"
     56 "Ogun_Rural"
     57 "Ondo_Urban"
     58 "Ondo_Rural"
     59 "Osun_Urban"
     60 "Osun_Rural"
     61 "Oyo_Urban"
     62 "Oyo_Rural"
     63 "Plateau_Urban"
     64 "Plateau_Rural"
     65 "Rivers_Urban"
     66 "Rivers_Urban"
     67 "Rivers_Rural"
     68 "Rivers_Rural"
     69 "Sokoto_Urban"
     70 "Sokoto_Rural"
     71 "Taraba_Urban"
     72 "Taraba_Rural"
     73 "Yobe_Urban"
     74 "Yobe_Rural"
     75 "Zamfara_Urban"
     76 "Zamfara_Rural"
  /V024    
      1 "Sokoto"
      2 "Zamfara"
      3 "Katsina"
      4 "Jigawa"
      5 "Yobe"
      6 "Borno"
      7 "Adamawa"
      8 "Gombe"
      9 "Bauchi"
     10 "Kano"
     11 "Kaduna"
     12 "Kebbi"
     13 "Niger"
     14 "FCT"
     15 "Nasarawa"
     16 "Plateau"
     17 "Taraba"
     18 "Benue"
     19 "Kogi"
     20 "Kwara"
     21 "Oyo"
     22 "Osun"
     23 "Ekiti"
     24 "Ondo"
     25 "Edo"
     26 "Anambra"
     27 "Enugu"
     28 "Ebonyi"
     29 "Cross River"
     30 "Akwa Ibom"
     31 "Abia"
     32 "Imo"
     33 "Rivers"
     34 "Bayelsa"
     35 "Delta"
     36 "Lagos"
     37 "Ogun"
  /V025    
      1 "Urban"
      2 "Rural"
  /V026    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V034    
      0 "Husband not in household"
  /V042    
      0 "Not selected"
      1 "Selected"
  /V045A   
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
  /V045B   
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
      5 "Fulfulde"
      6 "Other"
  /V045C   
      1 "English"
      2 "Hausa"
      3 "Yoruba"
      4 "Igbo"
      5 "Fulfulde"
      6 "Other"
  /V046    
      0 "No"
      1 "Yes"
  /V101    
      1 "Sokoto"
      2 "Zamfara"
      3 "Katsina"
      4 "Jigawa"
      5 "Yobe"
      6 "Borno"
      7 "Adamawa"
      8 "Gombe"
      9 "Bauchi"
     10 "Kano"
     11 "Kaduna"
     12 "Kebbi"
     13 "Niger"
     14 "FCT"
     15 "Nasarawa"
     16 "Plateau"
     17 "Taraba"
     18 "Benue"
     19 "Kogi"
     20 "Kwara"
     21 "Oyo"
     22 "Osun"
     23 "Ekiti"
     24 "Ondo"
     25 "Edo"
     26 "Anambra"
     27 "Enugu"
     28 "Ebonyi"
     29 "Cross River"
     30 "Akwa Ibom"
     31 "Abia"
     32 "Imo"
     33 "Rivers"
     34 "Bayelsa"
     35 "Delta"
     36 "Lagos"
     37 "Ogun"
  /V102    
      1 "Urban"
      2 "Rural"
  /V106    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /V107    
      0 "No years completed at level V106"
  /V113    
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Piped to neighbor"
     14 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE FROM SPRING"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     72 "Sachet water"
     96 "Other"
     97 "Not a dejure resident"
  /V115    
    996 "On premises"
    997 "Not a dejure resident"
    998 "Don't know"
  /V116    
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
     97 "Not a dejure resident"
  /V119    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V120    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V121    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V122    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V123    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V124    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V125    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V127    
     10 "NATURAL"
     11 "Earth/sand"
     12 "Dung"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm/bamboo"
     30 "FINISHED"
     31 "Parquet or polished wood"
     32 "Vinyl or asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "Other"
     97 "Not a dejure resident"
  /V128    
     10 "NATURAL"
     11 "No walls"
     12 "Cane/palm/trunks"
     13 "Dirt"
     20 "RUDIMENTARY"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Uncovered adobe"
     24 "Plywood"
     25 "Cardboard"
     26 "Reused wood"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks/shingles"
     96 "Other"
     97 "Not a dejure resident"
  /V129    
     10 "NATURAL"
     11 "No roof"
     12 "Thatch/palm leaf"
     13 "Grass"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     22 "Palm/bamboo"
     23 "Wood planks"
     24 "Cardboard"
     30 "FINISHED"
     31 "Metal/Zinc"
     32 "Wood"
     33 "Calamine/cement fiber"
     34 "Ceramic tiles"
     35 "Cement"
     36 "Roofing shingles"
     37 "Asbestos"
     96 "Other"
     97 "Not a dejure resident"
  /V130    
      1 "Catholic"
      2 "Other Christian"
      3 "Islam"
      4 "Traditionalist"
     96 "Other"
  /V131    
      1 "Abua"
      2 "Adra/Adarawa"
      3 "Adun"
      4 "Afcabeya"
      5 "Afemai"
      6 "Afizire"
      7 "Agatu"
      8 "Agbassa"
      9 "Agbor"
     10 "Afo"
     11 "Ajowa"
     12 "Akpa"
     13 "Akwai"
     14 "Akye"
     15 "Alago"
     16 "Amamong"
     17 "Amo"
     18 "Ana"
     19 "Anaguta"
     20 "Ankwai"
     21 "Annang"
     22 "Arab"
     23 "Arabo"
     24 "Arbar"
     25 "Arugu"
     26 "Aten/Atam"
     27 "Attakar"
     28 "Auchi"
     29 "Aulliminden"
     30 "Awo"
     31 "Ayetoro Gbede"
     32 "Badarare"
     33 "Bade/Badawe"
     34 "Bafeke"
     35 "Bagathiya"
     36 "Baggara"
     37 "Bagunge/Badagire"
     38 "Bahnake"
     39 "Baji/Biji"
     40 "Bajju"
     41 "Bambaro"
     42 "Bambuka"
     43 "Bandawa"
     44 "Banguji"
     45 "Bankalawa"
     46 "Bchama"
     47 "Barabaci"
     48 "Barawa"
     49 "Bargawa"
     50 "Bassa"
     51 "Bekworas"
     53 "Berom"
     54 "Bini/Edo"
     55 "Bogom"
     56 "Boiyawa/Bozaya"
     57 "Bolawa/Bolewa"
     59 "Buduma"
     60 "Buko"
     61 "Bura/Babur"
     62 "Buzu"
     63 "Byazhi"
     64 "Calabar"
     65 "Chala"
     66 "Chamba"
     67 "Chiba"
     68 "Chibok(g)"
     69 "Chip"
     70 "Dadiya"
     71 "Badakare/Dakarkari"
     72 "Dakka/Doka"
     73 "Dangula"
     74 "Daurawa/Dagarawa"
     75 "Defaka"
     76 "Degima"
     77 "Delta Ibo"
     78 "Dibo"
     79 "Diguza"
     80 "Djerma"
     81 "Dmoko"
     82 "Dolchi"
     83 "Ebira/Igbira"
     84 "Ebu"
     85 "Efik"
     86 "Egba"
     87 "Egbado"
     88 "Eggon"
     89 "Egun"
     90 "Eket"
     91 "Ekoi"
     92 "Ekpeye/Afisa/Epie"
     94 "Ekulu"
     95 "Eleme"
     96 "Emu"
     97 "Esan"
     98 "Etina"
     99 "Etsako"
    100 "Etulo"
    101 "Hadejawa"
    102 "Fanso"
    103 "Femawa"
    104 "Fer"
    105 "Filiya/Fali"
    106 "Fon"
    107 "Foron"
    108 "French"
    109 "Fulani"
    110 "Gamaku"
    111 "Gamaru"
    112 "Gamuni"
    113 "Gana Gana"
    114 "Ganawuri"
    115 "Gbaju/Gbagi"
    116 "Gede/Gude/Gai"
    117 "Gerawa"
    118 "Gizmawa"
    119 "Glauda"
    120 "Gmenchi"
    121 "Gomo/Gamoyaya"
    122 "Gobiri/Gobirawa/Bogobiri"
    123 "Gujjurawa"
    124 "Guemai"
    125 "Gumbarawa"
    126 "Gunganchi"
    127 "Gwandara"
    128 "Gwantu"
    129 "Hankwe"
    130 "Hausa"
    131 "Higgi"
    132 "Ibariba"
    133 "Ibibio"
    134 "Ichen"
    135 "Idanre"
    136 "Idoma"
    137 "Igala"
    138 "Igbo/Ibo"
    139 "Igede"
    140 "Ijaw/Izon"
    141 "Ijede"
    142 "Ijeme"
    143 "Ika"
    144 "Ikajo"
    145 "Ikara"
    146 "Ikpeshi"
    147 "Ikpide"
    148 "Ikulu"
    149 "Ikwere"
    150 "Ilaje"
    151 "Irigwe"
    152 "Ishan"
    153 "Isoko"
    154 "Itsekiri"
    155 "Jaba"
    156 "Jajiri"
    157 "Jakatoe"
    158 "Jaku"
    159 "Jara"
    160 "Jarawa"
    162 "Jibu"
    163 "Jonjo"
    164 "Jukun"
    165 "Kabawa"
    166 "Kadara"
    167 "Kagoma"
    168 "Kagoro"
    169 "Kaka"
    170 "Kakanda"
    171 "Kamantam"
    172 "Kambari"
    173 "Kambu/Kangu"
    174 "Kamuku"
    175 "Kanakuru"
    176 "Kanawa"
    177 "Kaninko"
    178 "Kantanawa"
    179 "Kanuri/Beriberi"
    180 "Manga"
    181 "Karekare"
    182 "Kataf/Atyap"
    183 "Kento"
    184 "Kibaku"
    185 "Kilba"
    186 "Kirdi"
    187 "Kodki"
    188 "Kofyar"
    189 "Kona"
    190 "Koro"
    191 "Koto"
    192 "Kuenuem"
    193 "Kumbo"
    194 "Kunkawa/Kawa"
    195 "Kurama"
    196 "Kuteb"
    197 "Kuturm"
    198 "Kwale/Ukwuani"
    199 "Kwanzo"
    200 "Lagelu"
    201 "Lantang"
    202 "Lemoro"
    203 "Loh"
    204 "Lunguda"
    205 "Maba/Mbadowa"
    206 "Mada"
    207 "Mafa/Maka/Maga"
    208 "Mambila"
    209 "Mandara"
    210 "Mangus/Manju"
    211 "Marghi/mangi"
    212 "Mbwa"
    213 "Mingo"
    214 "Mirnang"
    215 "Montor"
    216 "Mtchiga/Michika"
    217 "Mumuye"
    218 "Munga"
    219 "Mupung"
    220 "Mushere"
    221 "Mwagavol"
    222 "Naiawum"
    223 "Namoen"
    224 "Ndokwa"
    225 "Ndola"
    226 "Ngamo"
    227 "Ukale"
    228 "Ngoshe"
    229 "Nili"
    230 "Ninnma"
    231 "Ninzom"
    232 "Nkoroo"
    233 "Nnebe"
    234 "Numana"
    235 "Nungu"
    236 "nunku"
    237 "Nupe"
    238 "Obubua"
    239 "Odu"
    240 "Ogoja"
    241 "Ogoni"
    242 "Ogugu"
    243 "Okori/Ogori"
    244 "Omele"
    245 "Ora"
    246 "Oron"
    247 "Owan"
    249 "Owo"
    250 "Pa'awa"
    251 "Paburi"
    252 "Paibun"
    253 "Panya"
    254 "Pasama"
    255 "Pero"
    256 "Piya"
    257 "Pyem"
    258 "Rukuba"
    259 "Rulere"
    260 "Rundawa"
    261 "Sayawa/Siyawa"
    262 "Sekere"
    263 "Sharawa"
    264 "Shomo"
    265 "Shuwa"
    266 "Somunka"
    267 "Sullubawa"
    268 "Sura"
    269 "Taira"
    270 "Tangale"
    272 "Tarok"
    273 "Tera"
    274 "Teskwa"
    275 "Tiguni ( ? )"
    276 "Tiv"
    277 "Tiyari"
    278 "Tula"
    279 "Ubaija"
    280 "Ugbia"
    281 "Uhionigbe"
    282 "Ukwuani"
    283 "Urhobo"
    284 "Uyo"
    285 "Uzaurue"
    286 "Uzeba"
    287 "Waja"
    288 "Waka"
    289 "Wanu"
    290 "Wari"
    291 "Warjawa"
    292 "Wodaabe"
    293 "Wurkum"
    294 "Yakurr"
    295 "Yandang"
    296 "Yendre"
    297 "Yonubi"
    298 "Yoruba"
    299 "Zabarmawa"
    301 "Kaje"
    302 "Igbanko"
    303 "Okori/Ogori"
    304 "Migili"
    305 "Gwari"
    306 "Uru"
    307 "Okirika"
    308 "Egi"
    309 "Ogba"
    310 "Moroa"
    311 "Marwa"
    312 "Toff"
    313 "Fulfulde"
    314 "Kabba/Okun"
    315 "Bakabe"
    316 "Burmanch"
    317 "Kalabari"
    320 "Miship"
    321 "Karimjo"
    322 "Kwa"
    323 "Angas"
    324 "Bobari"
    325 "Yarimawa"
    326 "Bakenga"
    327 "Agazawa"
    328 "Gwoza"
    329 "Zalidva"
    330 "Nyangdang"
    331 "Ngezim"
    332 "Hanbagda"
    333 "Njanyi"
    334 "Dumak"
    335 "Kwalla"
    336 "Yeskwa and Mubula"
    337 "Bile"
    338 "Offa"
    339 "Yungur"
    340 "Pura Pura"
    341 "Rindre"
    342 "Dukawa"
    343 "Ningi"
    344 "Cham"
    345 "Kamo"
    346 "Lala"
    347 "Laru"
    348 "Lisa"
    349 "Gaanda"
    350 "Ezza"
    351 "Kubasawa."
    352 "Gusu"
    353 "Ikpoma"
    354 "Buh"
    355 "Mushere"
    356 "Chakeem"
    357 "Jipal"
    358 "Ugeb"
    359 "Koma"
    360 "Verre/Kila"
    361 "Zuru"
    362 "Honna"
    363 "Kapsiki"
    364 "Jere"
    365 "Gizi Yobe"
    366 "Karekare"
    367 "Kulere"
    368 "Beteer"
    369 "Bashama"
    370 "Antocha"
    371 "Baruba/Baruntin"
    372 "Nezou"
    373 "Dibba"
    374 "Kanum"
    375 "Gasawa"
    376 "Muryan"
    377 "Bageri"
    378 "Ahu"
    379 "Basange"
    380 "Nakere"
    381 "Batunu"
    382 "Sanga"
    383 "Ohari"
    384 "Numuro"
    385 "Tangale"
    386 "Guruma"
    387 "Otuwo"
    388 "Batala"
    389 "Ogbo"
    390 "Egbema"
    391 "Dara"
    392 "Andoni"
    393 "Obolo"
    394 "Pegan"
    395 "Iyala"
    396 "Jibawa"
    397 "Mungaduso"
    398 "Okobo"
    996 "Others"
    998 "Don't Know"
  /V133    
     97 "Inconsistent"
  /V134    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V135    
      1 "Usual resident"
      2 "Visitor"
  /V139    
      0 "Abroad"
      1 "Sokoto"
      2 "Zamfara"
      3 "Katsina"
      4 "Jigawa"
      5 "Yobe"
      6 "Borno"
      7 "Adamawa"
      8 "Gombe"
      9 "Bauchi"
     10 "Kano"
     11 "Kaduna"
     12 "Kebbi"
     13 "Niger"
     14 "FCT"
     15 "Nasarawa"
     16 "Plateau"
     17 "Taraba"
     18 "Benue"
     19 "Kogi"
     20 "Kwara"
     21 "Oyo"
     22 "Osun"
     23 "Ekiti"
     24 "Ondo"
     25 "Edo"
     26 "Anambra"
     27 "Enugu"
     28 "Ebonyi"
     29 "Cross River"
     30 "Akwa Ibom"
     31 "Abia"
     32 "Imo"
     33 "Rivers"
     34 "Bayelsa"
     35 "Delta"
     36 "Lagos"
     37 "Ogun"
     97 "Not dejure resident"
  /V140    
      0 "Abroad"
      1 "Urban"
      2 "Rural"
      7 "Not a dejure resident"
  /V141    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
      7 "Not a dejure resident"
  /V149    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
  /V150    
      1 "Head"
      2 "Wife"
      3 "Daughter"
      4 "Daughter-in-law"
      5 "Granddaughter"
      6 "Mother"
      7 "Mother-in-law"
      8 "Sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "Don't know"
  /V151    
      1 "Male"
      2 "Female"
  /V152    
     97 "97+"
     98 "Don't know"
  /V153    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V155    
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
      4 "Blind/visually impaired"
  /V156    
      0 "No"
      1 "Yes"
  /V157    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V158    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V159    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V160    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V161    
      1 "Electricity"
      2 "Solar cooker"
      3 "LPG"
      4 "Natural gas"
      5 "Biogas"
      6 "Alcohol/ethanol"
      7 "Gasoline/diesel"
      8 "Kerosene/paraffin"
      9 "Coal/lignite"
     10 "Charcoal"
     11 "Wood"
     12 "Straw/shrubs/grass"
     13 "Agricultural crop"
     14 "Animal dung/waste"
     15 "Processed biomass (pellets) or woodchips"
     16 "Garbage/plastic"
     17 "Sawdust"
     95 "No food cooked in house"
     96 "Other"
     97 "Not a dejure resident"
  /V169A   
      0 "No"
      1 "Yes"
  /V169C   
      0 "No"
      1 "Yes"
  /V171A   
      0 "Never"
      1 "Yes, last 12 months"
      2 "Yes, before last 12 months"
      3 "Yes, can't establish when"
  /V171B   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V190    
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /V190A   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /ML101   
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /V459    
      0 "No"
      1 "Yes"
  /V460    
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /V461    
      0 "No"
      1 "Yes"
  /V468    
      0 "See specific questions"
      1 "Last birth only"
      2 "All births in last 5 years"
  /B0      
      0 "Single birth"
      1 "1st of multiple"
      2 "2nd of multiple"
      3 "3rd of multiple"
      4 "4th of multiple"
      5 "5th of multiple"
  /B4      
      1 "Male"
      2 "Female"
  /B5      
      0 "No"
      1 "Yes"
  /B6      
    100 "Died on day of birth"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
    997 "Inconsistent"
    998 "Don't know"
  /B9      
      0 "Respondent"
      1 "Father"
      2 "Other relative"
      3 "Someone else"
      4 "Lives elsewhere"
  /B10     
      0 "Month, year and day"
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /B13     
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
  /B15     
      0 "No"
      1 "Yes"
  /B16     
      0 "Not listed in household"
  /V208    
      0 "No births"
  /V209    
      0 "No births"
  /V213    
      0 "No or unsure"
      1 "Yes"
  /V214A   
    101 "Weeks: 1"
    199 "Weeks: number missing"
    201 "Months: 1"
    299 "Months: number missing"
  /V220    
      6 "6+"
  /V223    
      7 "Month - exact date"
      8 "None - date placed"
  /V237    
      0 "No"
      1 "Yes"
  /M2A     
      0 "No"
      1 "Yes"
  /M2B     
      0 "No"
      1 "Yes"
  /M2C     
      0 "No"
      1 "Yes"
  /M2D     
      0 "No"
      1 "Yes"
  /M2E     
      0 "No"
      1 "Yes"
  /M2F     
      0 "No"
      1 "Yes"
  /M2G     
      0 "No"
      1 "Yes"
  /M2H     
      0 "No"
      1 "Yes"
  /M2I     
      0 "No"
      1 "Yes"
  /M2J     
      0 "No"
      1 "Yes"
  /M2K     
      0 "No"
      1 "Yes"
  /M2L     
      0 "No"
      1 "Yes"
  /M2M     
      0 "No"
      1 "Yes"
  /M2N     
      0 "No: some care"
      1 "Yes: no care"
  /M13     
     98 "Don't know"
  /M13A    
    101 "Weeks: 1"
    199 "Weeks: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    998 "Don't know"
  /M14     
      0 "No antenatal visits"
     98 "Don't know"
  /M49A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49G    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49X    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49Z    
      0 "No"
      1 "Yes: don't know which drug taken"
      8 "Don't know"
  /M49Y    
      0 "No"
      1 "Yes, took no drug"
      8 "Don't know"
  /M57A    
      0 "No"
      1 "Yes"
  /M57B    
      0 "No"
      1 "Yes"
  /M57C    
      0 "No"
      1 "Yes"
  /M57D    
      0 "No"
      1 "Yes"
  /M57E    
      0 "No"
      1 "Yes"
  /M57F    
      0 "No"
      1 "Yes"
  /M57G    
      0 "No"
      1 "Yes"
  /M57H    
      0 "No"
      1 "Yes"
  /M57I    
      0 "No"
      1 "Yes"
  /M57J    
      0 "No"
      1 "Yes"
  /M57K    
      0 "No"
      1 "Yes"
  /M57L    
      0 "No"
      1 "Yes"
  /M57M    
      0 "No"
      1 "Yes"
  /M57N    
      0 "No"
      1 "Yes"
  /M57O    
      0 "No"
      1 "Yes"
  /M57P    
      0 "No"
      1 "Yes"
  /M57Q    
      0 "No"
      1 "Yes"
  /M57R    
      0 "No"
      1 "Yes"
  /M57NA   
      0 "No"
      1 "Yes"
  /M57NB   
      0 "No"
      1 "Yes"
  /M57NC   
      0 "No"
      1 "Yes"
  /M57ND   
      0 "No"
      1 "Yes"
  /M57NE   
      0 "No"
      1 "Yes"
  /M57S    
      0 "No"
      1 "Yes"
  /M57T    
      0 "No"
      1 "Yes"
  /M57U    
      0 "No"
      1 "Yes"
  /M57V    
      0 "No"
      1 "Yes"
  /M57X    
      0 "No"
      1 "Yes"
  /ML1     
     98 "Don't know"
  /ML2     
      1 "Antenatal visit"
      2 "Another facility visit"
      3 "Community health extension worker"
      6 "Other source"
  /H22     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H31     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
  /H32A    
      0 "No"
      1 "Yes"
  /H32B    
      0 "No"
      1 "Yes"
  /H32C    
      0 "No"
      1 "Yes"
  /H32D    
      0 "No"
      1 "Yes"
  /H32E    
      0 "No"
      1 "Yes"
  /H32F    
      0 "No"
      1 "Yes"
  /H32G    
      0 "No"
      1 "Yes"
  /H32H    
      0 "No"
      1 "Yes"
  /H32I    
      0 "No"
      1 "Yes"
  /H32J    
      0 "No"
      1 "Yes"
  /H32K    
      0 "No"
      1 "Yes"
  /H32L    
      0 "No"
      1 "Yes"
  /H32M    
      0 "No"
      1 "Yes"
  /H32N    
      0 "No"
      1 "Yes"
  /H32O    
      0 "No"
      1 "Yes"
  /H32P    
      0 "No"
      1 "Yes"
  /H32Q    
      0 "No"
      1 "Yes"
  /H32R    
      0 "No"
      1 "Yes"
  /H32NA   
      0 "No"
      1 "Yes"
  /H32NB   
      0 "No"
      1 "Yes"
  /H32NC   
      0 "No"
      1 "Yes"
  /H32ND   
      0 "No"
      1 "Yes"
  /H32NE   
      0 "No"
      1 "Yes"
  /H32S    
      0 "No"
      1 "Yes"
  /H32T    
      0 "No"
      1 "Yes"
  /H32U    
      0 "No"
      1 "Yes"
  /H32V    
      0 "No"
      1 "Yes"
  /H32W    
      0 "No"
      1 "Yes"
  /H32X    
      0 "No"
      1 "Yes"
  /H32Y    
      0 "No: received treatment"
      1 "Yes: no treatment"
  /H32Z    
      0 "No"
      1 "Yes"
  /H46A    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Government health post"
     14 "Government mobile clinic"
     15 "Government CHW/fieldworker"
     16 "Other public sector"
     20 "PRIVATE SECTOR"
     21 "Private hospital"
     22 "Private clinic"
     23 "Private pharmacy"
     24 "Private doctor"
     25 "Private mobile clinic"
     26 "Private CHW/fieldworker"
     27 "Other private medical sector"
     30 "OTHER"
     31 "NGO hospital"
     32 "NGO clinic"
     33 "Other NGO medical sector"
     34 "Chemist shop/PPMV"
     35 "Traditional practitioner"
     36 "Market"
     37 "Itinerant drug seller"
     38 "Community-oriented resource-person"
     96 "Other"
  /H46B    
      0 "Same day"
     98 "Don't know"
  /H47     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H71     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HW16    
     97 "Inconsistent"
     98 "Don't know"
  /HW51    
      0 "Not in household"
  /HW52    
      1 "Granted"
      2 "Refused"
      3 "Not present/other"
  /HW53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HW55    
      0 "Measured"
      1 "Dead"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /HW56    
    997 "Inconsistent"
  /HW57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HW58    
      0 "No"
      1 "Yes"
  /ML0     
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /ML11    
      0 "No"
      1 "Yes, fever only"
      2 "Yes, cough only"
      3 "Both fever and cough"
      8 "Don't know"
  /ML12    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /ML13A   
      0 "No"
      1 "Yes"
  /ML13B   
      0 "No"
      1 "Yes"
  /ML13C   
      0 "No"
      1 "Yes"
  /ML13D   
      0 "No"
      1 "Yes"
  /ML13DA  
      0 "No"
      1 "Yes"
  /ML13E   
      0 "No"
      1 "Yes"
  /ML13AA  
      0 "No"
      1 "Yes"
  /ML13AB  
      0 "No"
      1 "Yes"
  /ML13F   
      0 "No"
      1 "Yes"
  /ML13G   
      0 "No"
      1 "Yes"
  /ML13H   
      0 "No"
      1 "Yes"
  /ML13I   
      0 "No"
      1 "Yes"
  /ML13J   
      0 "No"
      1 "Yes"
  /ML13K   
      0 "No"
      1 "Yes"
  /ML13L   
      0 "No"
      1 "Yes"
  /ML13M   
      0 "No"
      1 "Yes"
  /ML13N   
      0 "No"
      1 "Yes"
  /ML13O   
      0 "No"
      1 "Yes"
  /ML13P   
      0 "No"
      1 "Yes"
  /ML13X   
      0 "No"
      1 "Yes"
  /ML13Y   
      0 "No"
      1 "Yes, nothing taken"
  /ML13Z   
      0 "No"
      1 "Yes, don't know"
  /ML14A   
      0 "No"
      1 "Yes"
  /ML14B   
      0 "No"
      1 "Yes"
  /ML14Y   
      0 "No"
      1 "Yes"
  /ML14Z   
      0 "No"
      1 "Yes"
  /ML15A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML15B   
      7 "7+ days"
      8 "Don't know"
  /ML15C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML16A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML16B   
      7 "7+ days"
      8 "Don't know"
  /ML16C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML17A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML17B   
      7 "7+ days"
      8 "Don't know"
  /ML17C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML18A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML18B   
      7 "7+ days"
      8 "Don't know"
  /ML18C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML19A   
      0 "No"
      1 "Yes"
  /ML19B   
      0 "No"
      1 "Yes"
  /ML19C   
      0 "No"
      1 "Yes"
  /ML19D   
      0 "No"
      1 "Yes"
  /ML19E   
      0 "No"
      1 "Yes"
  /ML19F   
      0 "No"
      1 "Yes"
  /ML19X   
      0 "No"
      1 "Yes"
  /ML19Y   
      0 "No"
      1 "Yes"
  /ML19Z   
      0 "No"
      1 "Yes"
  /ML20A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML20B   
      7 "7+ days"
      8 "Don't know"
  /ML20C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML21A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML21B   
      7 "7+ days"
      8 "Don't know"
  /ML21C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML22A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML22B   
      7 "7+ days"
      8 "Don't know"
  /ML22C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML23A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML23B   
      7 "7+ days"
      8 "Don't know"
  /ML23C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML24C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML25A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML501   
      0 "No"
      1 "Yes"
  /ML501A  
      0 "No"
      1 "Yes"
  /ML501B  
      0 "No"
      1 "Yes"
  /ML501C  
      0 "No"
      1 "Yes"
  /ML501D  
      0 "No"
      1 "Yes"
  /ML501E  
      0 "No"
      1 "Yes"
  /ML501F  
      0 "No"
      1 "Yes"
  /ML501G  
      0 "No"
      1 "Yes"
  /ML501H  
      0 "No"
      1 "Yes"
  /ML501I  
      0 "No"
      1 "Yes"
  /ML501J  
      0 "No"
      1 "Yes"
  /ML501K  
      0 "No"
      1 "Yes"
  /ML501X  
      0 "No"
      1 "Yes"
  /ML501Z  
      0 "No"
      1 "Yes"
  /ML503   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /ML503A  
      0 "No"
      1 "Yes"
  /ML503B  
      0 "No"
      1 "Yes"
  /ML503C  
      0 "No"
      1 "Yes"
  /ML503D  
      0 "No"
      1 "Yes"
  /ML503E  
      0 "No"
      1 "Yes"
  /ML503F  
      0 "No"
      1 "Yes"
  /ML503G  
      0 "No"
      1 "Yes"
  /ML503H  
      0 "No"
      1 "Yes"
  /ML503I  
      0 "No"
      1 "Yes"
  /ML503J  
      0 "No"
      1 "Yes"
  /ML503K  
      0 "No"
      1 "Yes"
  /ML503X  
      0 "No"
      1 "Yes"
  /ML503Z  
      0 "No"
      1 "Yes"
  /ML505   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML506   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML507   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML508   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML509   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML510   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML511   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML512   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /ML513   
      0 "Disagree/less than half"
      1 "Agree/more than half"
      8 "Don't know/uncertain"
  /ML514   
      0 "Disagree/less than half"
      1 "Agree/more than half"
      8 "Don't know/uncertain"
  /S512A   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/uncertain"
  /SREGION 
      1 "North Central"
      2 "North East"
      3 "North West"
      4 "South East"
      5 "South South"
      6 "South West"
  /SBONNY  
      0 "No"
      1 "Yes"
  /S104A   
      0 "No"
      1 "Yes"
  /S104B   
      1 "Adult education"
      2 "Tsangaya"
      3 "Quaranic"
  /S211    
      0 "No births"
  /S411A   
      0 "No"
      1 "Yes"
  /S415A   
      0 "No"
      1 "Yes"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\NG81\NGKR81FL.sav'.
